# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""kinema: 横磁場イジングモデル (TFIM) の量子アニーリングシミュレータ
=====================================================================

Hamiltonian:
    H(t) = A(s(t)) · H_driver + B(s(t)) · H_problem
    H_driver  = -Σ_i h_x_i X_i              (サイト依存横磁場, bit-flip)
    H_problem = Z 演算子のみの k-local 多項式 (Z 基底で対角)

ユーザー入力:
    - H_p_diag : (2^N,) float64   Z 基底での H_problem 対角ベクトル
    - h_x      : (N,)   float64   サイト依存横磁場の振幅
    - psi0     : (2^N,) complex128 初期状態 (L2-normalize 済み, 必須明示指定)

ビット規約: bit 0 = LSB, x = Σ_i b_i · 2^i, spin σ_i = 1 - 2·b_i.

Usage
-----
>>> import numpy as np
>>> from kinema import IsingProblem, Schedule, QuantumAnnealer
>>> from kinema.initial_states import uniform_superposition
>>> from kinema.builders import diag_from_J_h
>>>
>>> n = 4
>>> J = np.random.default_rng(0).normal(size=(n, n)) / np.sqrt(n)
>>> J = (J + J.T) / 2; np.fill_diagonal(J, 0.0)
>>> h = np.zeros(n)
>>> prob = IsingProblem(
...     n=n,
...     H_p_diag=diag_from_J_h(J, h),
...     h_x=np.ones(n),
... )
>>> sched = Schedule.linear(T=30.0)
>>> psi0 = uniform_superposition(n)
>>> ann = QuantumAnnealer(prob, sched)
>>> res = ann.run(psi0, 0.0, sched.T, method="m2", n_steps=300)
>>> print(np.abs(res.psi_final[:8]) ** 2)   # 最終状態 |ψ(T)|^2 の冒頭 8 成分

設計詳細は ``docs/design/INDEX.md`` 参照. 各公開モジュールに対応する ``.pyi``
スタブ (``python/kinema/*.pyi``) を一次 API リファレンスとして読むことを
推奨する.
"""
import warnings
from kinema.annealer import QuantumAnnealer as QuantumAnnealer
from kinema.eigenstates import instantaneous_eigenstates as instantaneous_eigenstates
from kinema.observable import Observable as Observable
from kinema.problem import IsingProblem as IsingProblem
from kinema.result import QuantumResult as QuantumResult, Trajectory as Trajectory
from kinema.schedule import Schedule as Schedule
from kinema.simulator import AnnealingSimulator as AnnealingSimulator
from typing import Any
__all__ = ['AnnealingSimulator', 'IsingProblem', 'Observable', 'QuantumAnnealer', 'QuantumResult', 'Schedule', 'Trajectory', 'available_blas_threads', 'instantaneous_eigenstates', 'set_blas_threads', 'set_blas_threads_auto', 'show_config']

def set_blas_threads(n: int) -> None:
    """ロード済みの全 OpenBLAS pool のスレッド上限を ``n`` に統一する.

    Rust kernel が system BLAS に動的リンクするため, kinema を import した
    Python プロセスには numpy bundled / scipy bundled / system OpenBLAS の
    最大 3 つの BLAS pool が同居しうる. bundled 版はシンボル prefix が
    ``libscipy_openblas`` にリネームされており, ``OPENBLAS_NUM_THREADS``
    等の環境変数を全 pool で一貫して honor するとは限らない. 本関数は
    ``threadpoolctl.threadpool_limits`` 経由で BLAS API (``user_api='blas'``)
    を使う全 pool に API ベースで ``set_num_threads(n)`` を呼ぶ.

    用途と限界
    ----------
    本関数は **既に確保された BLAS pool 内で active thread 数を制限する**
    だけで, pool size 自体 (= プロセスが確保している OS thread 数) は
    縮まらない. OpenBLAS / MKL 等の thread pool は **プロセス起動時** に
    ``OPENBLAS_NUM_THREADS`` / ``MKL_NUM_THREADS`` などの環境変数で size が
    確定し, 以降は ``set_num_threads(n)`` で active 数を絞っても残りの
    thread は sleep 状態で stack / kernel resource を保持する.

    そのため:

    - **import 後に動的に active BLAS thread 数を絞りたい** シナリオでは
      本関数を使う. rayon 経路と併用する際の **推奨 default** は
      :func:`set_blas_threads_auto` (issue #116 perf 実証で
      ``OPENBLAS_NUM_THREADS=8`` 相当で 1.52× speedup). 明示的に 1
      thread に絞りたい (= 完全に隔離したい) ときのみ
      ``set_blas_threads(1)`` を直接呼ぶ.
    - **per-process thread budget の隔離** が要件のシナリオ
      (multiprocessing / Slurm job array で 1 プロセスあたりの thread 数を
      物理的に制限したい) では, ``kinema`` / ``numpy`` を import する
      **前** に環境変数 (``OPENBLAS_NUM_THREADS`` / ``MKL_NUM_THREADS`` /
      ``VECLIB_MAXIMUM_THREADS`` / ``OMP_NUM_THREADS`` / ``RAYON_NUM_THREADS``)
      を set すること. 詳細パターンは ``docs/quickstart.md`` 末尾節
      "並列ジョブ実行時のスレッド数制御" 参照.

    Parameters
    ----------
    n
        各 BLAS pool に設定する active thread 数の上限. 1 以上の整数.
    """
    ...

def available_blas_threads() -> int:
    """現在のプロセスで実効的に利用可能な BLAS スレッド数を返す.

    複数の BLAS pool (Apple Accelerate / OpenBLAS / MKL ...) が同居する場合は
    ``threadpoolctl.threadpool_info()`` の ``num_threads`` の最小値を採り,
    さらに ``os.process_cpu_count()`` で上限をキャップする (プロセスへの
    CPU 割当が BLAS 設定より小さければそちらが律速).

    Returns
    -------
    int
        有効な BLAS スレッド予算. 最小 1.
    """
    ...

def set_blas_threads_auto() -> int:
    """:func:`_recommended_blas_threads` の値を適用し, 適用した値を返す.

    内部で :func:`set_blas_threads` を呼んで全 BLAS pool の active thread
    数を推奨値に統一する. issue #116 で確立した「rayon 経路でも
    BLAS=1 ではなく ``process_cpu_count / 8`` 程度を使う」という
    新方針の便利関数.

    冪等. 同じ環境変数 / cpu 割当下では何度呼んでも同じ値を返す.

    Examples
    --------
    >>> import kinema
    >>> kinema.set_blas_threads_auto()   # 推奨 default を適用  # doctest: +SKIP
    8
    >>> kinema.set_blas_threads(1)       # 明示 override            # doctest: +SKIP

    Returns
    -------
    int
        実際に適用した active BLAS thread 数.
    """
    ...

def show_config() -> None:
    """ビルド構成を stdout に dump する (``numpy.show_config()`` 相当, issue #103).

    repo 同梱の ``.cargo/config.toml`` で ``-C target-cpu=native`` が default
    適用されるが, それが実際に build 時の SIMD 経路 (``wide::f64x4``) に
    反映されたか (= AVX2 / AVX-512 / NEON dispatch を選んだか) を確認する
    ためのヘルパ. ``uv add git+...`` 経由のソースビルド直後やベンチを取る
    前の build profile 確認に用いる.

    出力項目:

    * ``version``: ``importlib.metadata.version("kinema")`` で取得.
    * ``target arch`` / ``target OS``: Rust 拡張のビルドターゲット
      (``_rust.__target_arch__`` / ``__target_os__``, ``std::env::consts``
      由来).
    * ``cargo features``: ``__has_blas__`` / ``__has_rayon__`` / ``__has_simd__``
      (``cfg!(feature = "...")`` 由来).
    * ``target_features``: ``__has_avx2__`` / ``__has_fma__`` /
      ``__has_avx512f__`` / ``__has_neon__`` (``cfg!(target_feature = "...")``
      由来). ``target-cpu=native`` の効きを反映.

    Rust 拡張 (``kinema._rust``) が import できない環境では各行を
    ``unavailable`` と表示する.
    """
    ...
