# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""高レベル公開 API (``QuantumAnnealer`` / ``AnnealingSimulator``).

``QuantumAnnealer`` は ``IsingProblem`` + ``Schedule`` を受け取り,
``run(psi0, t0, t1, *, method=..., n_steps=...)`` で時間発展を実行して
``QuantumResult`` を返す one-shot 用途のファサード. 同じ問題・スケジュール
に対して異なる初期状態 / 区間で繰り返し実行できるよう, ``psi0`` は
コンストラクタではなく ``run`` 側で受け取る.

``AnnealingSimulator`` は同じ問題に対する step-wise stateful API.
Phase 1 では ``QuantumAnnealer`` のみ提供する (``AnnealingSimulator`` は
Phase 5 で導入予定).

仕様 (Phase 1 + Phase 2)
------------------------
* サポート ``method``: ``"m2"`` (固定 dt M2 中点則, Phase 1), ``"trotter"``
  (固定 dt Strang 2 次 Trotter, Phase 2), ``"trotter_suzuki4"`` (固定 dt
  Suzuki S_4 4 次 Trotter, Phase 2 末). それ以外は ``NotImplementedError``.
* ``save_tlist`` 引数は **API 互換性のために予約済み** だが本リリースでは
  ``None`` のみ受け付ける (非 ``None`` で ``NotImplementedError``).
  Phase 5 の ``QuantumResult.times`` / ``states`` 拡張と一緒に有効化する.
* 観測量経路 (``observables=...``) も Phase 5 で追加予定. 現状は
  ``QuantumResult.observables_history = {}`` 固定.

実装方針: ``kryanneal.krylov.evolve_schedule_m2`` / ``evolve_schedule_trotter``
/ ``evolve_schedule_trotter_suzuki4`` (固定 dt driver) を内部で呼ぶ薄い
ラッパ. 入力検証 (shape / dtype / L2-normalize) を本クラスで集中させ,
krylov 層は数値計算に専念させる. ``m`` / ``krylov_tol`` は ``"m2"`` 経路で
のみ意味を持ち, ``"trotter"`` / ``"trotter_suzuki4"`` 経路は Lanczos を
使わないため両パラメータは無視される.
"""
from __future__ import annotations as annotations
from typing import Literal as Literal
import numpy as np
from kryanneal.krylov import evolve_schedule_m2 as evolve_schedule_m2, evolve_schedule_trotter as evolve_schedule_trotter, evolve_schedule_trotter_suzuki4 as evolve_schedule_trotter_suzuki4
from kryanneal.problem import IsingProblem as IsingProblem
from kryanneal.result import QuantumResult as QuantumResult
from kryanneal.schedule import Schedule as Schedule
from typing import Any
__all__ = ['QuantumAnnealer']

class QuantumAnnealer:
    """One-shot 時間発展ファサード.

    Parameters
    ----------
    problem
        ``IsingProblem``. ``H_p_diag`` / ``h_x`` を保持する.
    schedule
        ``Schedule``. ``coeffs_at(t)`` から ``(A(s(t)), B(s(t)))`` を得る.
    m
        Lanczos / Krylov 部分空間次元の既定値 (``run`` 内で使用).
        ``m >= 1``. 既定 ``24``.
    krylov_tol
        Lanczos の β 打切り閾値. ``β_k < tol`` で部分空間を切る.
        既定 ``1e-12``.

    Raises
    ------
    ValueError
        ``m < 1`` または ``krylov_tol < 0`` の場合.
    """
    problem: Any
    schedule: Any
    m: Any
    krylov_tol: Any

    def __init__(self, problem: IsingProblem, schedule: Schedule, *, m: int=24, krylov_tol: float=1e-12) -> None:
        ...

    def run(self, psi0: np.ndarray, t0: float, t1: float, *, method: Literal['m2', 'trotter', 'trotter_suzuki4']='m2', n_steps: int, save_tlist: np.ndarray | None=None) -> QuantumResult:
        """``[t0, t1]`` 区間で時間発展を実行し ``QuantumResult`` を返す.

        Parameters
        ----------
        psi0
            shape ``(2**n,)`` complex128 の初期状態. L2-normalize 済み
            (``|‖psi0‖ - 1| < 1e-10``) であることを検証する.
        t0, t1
            積分区間. ``t1 > t0``.
        method
            プロパゲータ. ``"m2"`` (固定 dt M2 中点則, Phase 1),
            ``"trotter"`` (固定 dt Strang 2 次 Trotter, Phase 2), または
            ``"trotter_suzuki4"`` (固定 dt Suzuki S_4 4 次 Trotter, Phase 2 末).
            Trotter 系経路は Lanczos を呼ばないため ``m`` / ``krylov_tol``
            は無視される.
        n_steps
            固定 step 数 (``n_steps >= 1``). 等間隔 ``dt = (t1 - t0) /
            n_steps`` で進める.
        save_tlist
            観測時刻列 (Phase 5 で実装予定). 現状は ``None`` 以外を
            渡すと ``NotImplementedError``.

        Returns
        -------
        QuantumResult
            ``psi_final`` / ``n_steps`` / ``n_matvec`` を持つ result.
            Phase 1 / Phase 2 では ``t_history = None``,
            ``observables_history = {}``. ``n_matvec`` は経路ごとに以下:

            * ``"m2"``: ``n_steps × m`` (Lanczos の matvec 見積もり).
            * ``"trotter"``: ``n_steps × (N + 1)`` (phase pass 1 + bit-flip
              pass N の dim-walk 見積もり; ``docs/design.md`` §4.4 参照).
            * ``"trotter_suzuki4"``: ``n_steps × 5 × (N + 1)`` (5 sub-step
              × Strang per-step コスト).

        Raises
        ------
        ValueError
            入力検証失敗 (``psi0`` の shape / dtype / 非正規化, ``n_steps <
            1``, ``t1 <= t0``).
        NotImplementedError
            ``method`` が ``"m2"`` / ``"trotter"`` / ``"trotter_suzuki4"``
            以外, または ``save_tlist`` が ``None`` でない場合.
        """
        ...
