# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""高レベル公開 API (``QuantumAnnealer`` / ``AnnealingSimulator``).

``QuantumAnnealer`` は ``IsingProblem`` + ``Schedule`` を受け取り,
``run(psi0, t0, t1, *, method=..., n_steps=...)`` で時間発展を実行して
``QuantumResult`` を返す one-shot 用途のファサード. 同じ問題・スケジュール
に対して異なる初期状態 / 区間で繰り返し実行できるよう, ``psi0`` は
コンストラクタではなく ``run`` 側で受け取る.

``AnnealingSimulator`` は同じ問題に対する step-wise stateful API.
Phase 1 では ``QuantumAnnealer`` のみ提供する (``AnnealingSimulator`` は
Phase 5 で導入予定).

仕様 (Phase 1 + Phase 2 + Phase 3 + Phase 4)
--------------------------------------------
* サポート ``method``: ``"m2"`` (固定 dt M2 中点則, Phase 1), ``"trotter"``
  (固定 dt Strang 2 次 Trotter, Phase 2), ``"trotter_suzuki4"`` (固定 dt
  Suzuki S_4 4 次 Trotter, Phase 2 末), ``"cfm4"`` (固定 dt CFM4:2
  commutator-free Magnus, Phase 3), ``"cfm4_adaptive_richardson"`` (Phase 4
  C3, step-doubling Richardson + PI controller). それ以外は
  ``NotImplementedError``.
* ``save_tlist`` 引数は **API 互換性のために予約済み** だが本リリースでは
  ``None`` のみ受け付ける (非 ``None`` で ``NotImplementedError``).
  Phase 5 の ``QuantumResult.times`` / ``states`` 拡張と一緒に有効化する.
* 観測量経路 (``observables=...``) も Phase 5 で追加予定. 現状は
  ``QuantumResult.observables_history = {}`` 固定.
* adaptive 経路では ``n_steps`` を渡さない (``None`` で良い). 代わりに
  ``atol`` (PI 局所誤差閾値; driver の ``tol_step`` に map) と ``dt_init``
  (初期 dt 提案; driver の ``dt0`` に map) を kw-only で受ける. どちらも
  ``None`` のときは driver 既定値 (``tol_step=1e-8``, ``dt0=0.5``) を使う.
  ``dt_init="auto"`` を渡すと linear schedule の Magnus 級数 T スケーリング
  (s-space scaling invariance, ``docs/design.md`` §5.3) から導いた保守値
  ``dt0 = max(min(c · T^β, T), floor)`` (既定 ``c=0.1, β=0.5, floor=1e-3``)
  を使う. PI controller の warmup step (default 0.5 → optimal dt への成長)
  を T 依存に削減する DX 改善 (issue #43 A).
* ``dt_max="auto"`` を渡すと Gershgorin 上界
  ``‖H‖_est = Σ_i |h_x_i| + max_k |H_p_diag[k]|`` から Lanczos capacity
  自動見積もり ``dt_max = max(min(10·dt0, 4m / ‖H‖_est), dt0)`` で
  ``dt · ‖H‖ ≲ 4m`` の安全領域にクランプする (issue #43 B). 大 N で
  ``‖H‖ ∝ N`` が支配的になる領域で PI controller を守備に機能させる.
* ``m_max`` を渡すと adaptive Richardson 経路の Lanczos 部分空間次元の
  上限を ``self.m`` の代わりに ``m_max`` で上書きする (issue #43 C, 簡略
  scope). step-doubling Richardson 推定子が Lanczos breakdown も embedded
  error として検出するため, ``m_max=16`` 等まで下げて per-step matvec を
  30% 程度削減しても fail-safe で動作する (本来 PI controller が dt を
  絞ることで精度を担保). β_k < ``krylov_tol`` で Lanczos 早期打切が
  既存実装で効くため, ``m_eff ≤ m_max`` の運用. ``m_eff`` 累積統計の
  ``QuantumResult`` 露出は Rust API 拡張 (``lanczos_propagate`` の戻り値
  追加) が必要なため本フェーズでは保留 (``docs/design.md`` §5.3 参照).

実装方針: ``kryanneal.krylov.evolve_schedule_m2`` /
``evolve_schedule_trotter`` / ``evolve_schedule_trotter_suzuki4`` /
``evolve_schedule_cfm4`` (固定 dt driver) / ``evolve_schedule_adaptive_richardson``
(adaptive driver) を内部で呼ぶ薄いラッパ. 入力検証 (shape / dtype /
L2-normalize) を本クラスで集中させ, krylov 層は数値計算に専念させる.
``m`` / ``krylov_tol`` は ``"m2"`` / ``"cfm4"`` / ``"cfm4_adaptive_richardson"``
経路でのみ意味を持ち, ``"trotter"`` / ``"trotter_suzuki4"`` 経路は Lanczos を
使わないため両パラメータは無視される.
"""
from __future__ import annotations as annotations
from typing import Literal as Literal
import numpy as np
from kryanneal.krylov import evolve_schedule_adaptive_richardson as evolve_schedule_adaptive_richardson, evolve_schedule_cfm4 as evolve_schedule_cfm4, evolve_schedule_m2 as evolve_schedule_m2, evolve_schedule_trotter as evolve_schedule_trotter, evolve_schedule_trotter_suzuki4 as evolve_schedule_trotter_suzuki4
from kryanneal.problem import IsingProblem as IsingProblem
from kryanneal.result import QuantumResult as QuantumResult
from kryanneal.schedule import Schedule as Schedule
from typing import Any
__all__ = ['QuantumAnnealer']

class QuantumAnnealer:
    """One-shot 時間発展ファサード.

    Parameters
    ----------
    problem
        ``IsingProblem``. ``H_p_diag`` / ``h_x`` を保持する.
    schedule
        ``Schedule``. ``coeffs_at(t)`` から ``(A(s(t)), B(s(t)))`` を得る.
    m
        Lanczos / Krylov 部分空間次元の既定値 (``run`` 内で使用).
        ``m >= 1``. 既定 ``24``.
    krylov_tol
        Lanczos の β 打切り閾値. ``β_k < tol`` で部分空間を切る.
        既定 ``1e-12``.

    Raises
    ------
    ValueError
        ``m < 1`` または ``krylov_tol < 0`` の場合.
    """
    problem: Any
    schedule: Any
    m: Any
    krylov_tol: Any

    def __init__(self, problem: IsingProblem, schedule: Schedule, *, m: int=24, krylov_tol: float=1e-12) -> None:
        ...

    def run(self, psi0: np.ndarray, t0: float, t1: float, *, method: Literal['m2', 'trotter', 'trotter_suzuki4', 'cfm4', 'cfm4_adaptive_richardson']='m2', n_steps: int | None=None, atol: float | None=None, dt_init: float | Literal['auto'] | None=None, dt_max: float | Literal['auto'] | None=None, m_max: int | None=None, save_tlist: np.ndarray | None=None) -> QuantumResult:
        """``[t0, t1]`` 区間で時間発展を実行し ``QuantumResult`` を返す.

        Parameters
        ----------
        psi0
            shape ``(2**n,)`` complex128 の初期状態. L2-normalize 済み
            (``|‖psi0‖ - 1| < 1e-10``) であることを検証する.
        t0, t1
            積分区間. ``t1 > t0``.
        method
            プロパゲータ. ``"m2"`` (固定 dt M2 中点則, Phase 1),
            ``"trotter"`` (固定 dt Strang 2 次 Trotter, Phase 2),
            ``"trotter_suzuki4"`` (固定 dt Suzuki S_4 4 次 Trotter, Phase 2 末),
            ``"cfm4"`` (固定 dt CFM4:2 commutator-free Magnus, Phase 3),
            または ``"cfm4_adaptive_richardson"`` (Phase 4 C3,
            step-doubling Richardson + PI controller). Trotter 系経路は
            Lanczos を呼ばないため ``m`` / ``krylov_tol`` は無視される.
            ``"cfm4"`` / ``"cfm4_adaptive_richardson"`` は M2 と同じく
            Lanczos を介すので ``m`` / ``krylov_tol`` が有効.
        n_steps
            固定 dt 経路の step 数 (``n_steps >= 1``). 等間隔 ``dt =
            (t1 - t0) / n_steps`` で進める. adaptive 経路では渡さない
            (``None`` で良い; 渡しても無視される).
        atol
            adaptive 経路の局所誤差閾値. driver の ``tol_step`` に map
            される. ``None`` のときは driver 既定値 ``1e-8`` を使う.
            固定 dt 経路では無視される.
        dt_init
            adaptive 経路の初期 dt 提案. driver の ``dt0`` に map される.
            ``None`` のときは driver 既定値 ``0.5`` を使う. 固定 dt 経路
            では無視される. ``"auto"`` を渡すと
            ``dt0 = max(min(c · T^β, T), _AUTO_DT_INIT_FLOOR)``
            (T = ``t1 - t0``, 既定 ``c=0.1, β=0.5, floor=1e-3``) で解決し,
            PI controller の warmup step を T 依存で削減する
            (s-space scaling invariance, ``docs/design.md`` §5.3,
            issue #43 A). 例えば ``T=100`` で ``dt0=1.0``, ``T=1`` で
            ``dt0=0.1``, ``T=0.01`` で ``dt0=0.01`` (床値より大きいので
            formula 値) → driver default ``0.5`` 比でいずれも warmup を
            短縮する保守値となる.
        dt_max
            adaptive 経路の最大 dt 上限. driver の ``dt_max`` に map される.
            ``None`` のときは driver 既定値 ``10 · dt0`` を使う. 固定 dt
            経路では無視される. ``"auto"`` を渡すと Gershgorin 上界による
            Lanczos capacity 自動見積もり
            ``dt_max = max(min(10·dt0, 4m / ‖H‖_est), dt0)``,
            ``‖H‖_est = Σ_i |h_x_i| + max_k |H_p_diag[k]|`` で解決し,
            ``dt · ‖H‖ ≲ 4m`` の Lanczos safe 領域に強制クランプする
            (issue #43 B, ``docs/design.md`` §5.3). 大 N で ``‖H‖ ∝ N``
            が支配的になる領域で PI controller が暴走しないよう守備に
            機能する. step-doubling Richardson が breakdown を検出する
            ので fail-safe で動作する (Lanczos 容量を僅かに超えても
            embedded error 経由で dt が縮む).
        m_max
            adaptive Richardson 経路の Lanczos 部分空間次元の上限。
            ``None`` (default) のときは ``self.m`` (コンストラクタ既定 24)
            をそのまま使う。整数を指定すると ``self.m`` を上書きして
            driver の Lanczos 部分空間次元として用いる (issue #43 C,
            簡略 scope)。step-doubling Richardson 推定子が Lanczos
            breakdown も embedded error として検出する fail-safe を
            活かし, ``m_max=16`` 等で per-step matvec を 30% 程度削減
            する運用を許容する (Richardson が破綻を検知すれば PI
            controller が dt を絞り精度を維持)。``β_k < krylov_tol``
            の早期打切が既存実装で効くため, 実効次元は ``m_eff ≤
            m_max`` になる。固定 dt 経路では無視される。
            ``m_eff`` 累積統計の ``QuantumResult`` 露出は Rust API 拡張
            (``lanczos_propagate`` の戻り値追加 + PyO3 plumbing) が
            必要なため本フェーズでは保留 (``docs/design.md`` §5.3 参照)。
        save_tlist
            観測時刻列 (Phase 5 で実装予定). 現状は ``None`` 以外を
            渡すと ``NotImplementedError``.

        Returns
        -------
        QuantumResult
            ``psi_final`` / ``n_steps`` / ``n_matvec`` / ``success`` /
            ``method`` / ``n_steps_actual`` を持つ result.
            ``t_history = None``, ``observables_history = {}`` (Phase 5 で
            観測量を一緒に格納予定). ``n_matvec`` は経路ごとに以下:

            * ``"m2"``: ``n_steps × m`` (Lanczos の matvec 見積もり).
            * ``"trotter"``: ``n_steps × (N + 1)`` (phase pass 1 + bit-flip
              pass N の dim-walk 見積もり; ``docs/design.md`` §4.4 参照).
            * ``"trotter_suzuki4"``: ``n_steps × 5 × (N + 1)`` (5 sub-step
              × Strang per-step コスト).
            * ``"cfm4"``: ``n_steps × 2m`` (CFM4:2 は 1 step あたり Lanczos
              を 2 回呼ぶため M2 の 2 倍).
            * ``"cfm4_adaptive_richardson"``: ``n_steps_actual × 6m``
              (full CFM4:2 ``2m`` + half×2 CFM4:2 ``4m`` = ``6m``,
              ``docs/design.md`` §5.3).

            ``n_steps`` は固定 dt 経路では要求 step 数, adaptive 経路では
            実 step 数 (``n_steps_actual`` と同値) を返す.

        Raises
        ------
        ValueError
            入力検証失敗 (``psi0`` の shape / dtype / 非正規化,
            固定 dt 経路で ``n_steps`` 不指定 / ``n_steps < 1``, ``t1 <= t0``).
        NotImplementedError
            ``method`` がサポート対象外, または ``save_tlist`` が
            ``None`` でない場合.
        RuntimeError
            adaptive 経路で ``max_rejects`` 連続超過したとき (driver から
            伝播).
        """
        ...
