# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""Krylov + Magnus 時間発展ドライバ.

ここに **公開 driver 関数** (``evolve_schedule_*``) と **Python リファレンス
実装** を置く. Rust 拡張 (``kryanneal._rust``) が利用可能なら fast path に
ディスパッチし, 利用不可なら Python リファレンスで silent fallback する
契約 (詳細は ``docs/design.md`` §3, §5).

Phase 1 実装範囲
----------------
* ``evolve_schedule_m2``: 固定 dt の M2 中点則ドライバ.
* ``_python_lanczos_propagate``: 純 NumPy の Lanczos 短時間プロパゲータ
  リファレンス.
* ``_python_m2_step``: 純 NumPy の M2 中点則 1 step リファレンス.

Phase 2 で Trotter (Strang 2 次) 経路を追加:

* ``evolve_schedule_trotter``: 固定 dt の Strang Trotter ドライバ.
* ``_python_trotter_step``: 純 NumPy の Strang 1 step リファレンス
  (Rust 拡張 ``_rust.trotter_step_py`` と ``rel < 1e-13`` で一致する契約).

Phase 3 で CFM4:2, Phase 4 で adaptive driver
(``evolve_schedule_adaptive_m2`` / ``evolve_schedule_adaptive_richardson``)
を追加する.

Rust 拡張へのアクセスは ``kryanneal._rust`` を **遅延 import** で行う:
``_rust`` のロード失敗 (拡張未ビルド環境) を ``ImportError`` で捕捉して
``_rust`` モジュール参照を ``None`` にし, fast path を選ぶ関数側で
``None`` を見て Python リファレンスにフォールバックする.
"""
from __future__ import annotations as annotations
import importlib
from types import ModuleType as ModuleType
from typing import Callable as Callable
import numpy as np
from kryanneal.schedule import Schedule as Schedule
from typing import Any
__all__ = ['evolve_schedule_m2', 'evolve_schedule_trotter', 'evolve_schedule_trotter_suzuki4']

def evolve_schedule_m2(h_x: np.ndarray, h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int, *, m: int=24, krylov_tol: float=1e-12) -> tuple[np.ndarray, int]:
    """固定 dt = (t1 - t0) / n_steps の M2 中点則ドライバ.

    各 step で ``schedule.coeffs_at(t + dt/2)`` を評価して
    ``m2_midpoint_step`` を呼ぶ. Rust 拡張が import 済なら
    ``_rust.m2_midpoint_step_py`` を, そうでなければ Python リファレンス
    ``_python_m2_step`` を使う (silent fallback).

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).
    m
        Krylov 部分空間次元.
    krylov_tol
        Lanczos の β 打切り閾値.

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        累積 matvec 呼出回数 (Lanczos の ``m`` 回 × ``n_steps`` の見積もり).

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_trotter(h_x: np.ndarray, h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int) -> tuple[np.ndarray, int]:
    """固定 dt = (t1 - t0) / n_steps の Strang Trotter ドライバ.

    各 step で ``schedule.coeffs_at(t + dt/2)`` を評価して
    ``trotter_step`` を呼ぶ. Rust 拡張が import 済なら
    ``_rust.trotter_step_py`` を, そうでなければ Python リファレンス
    ``_python_trotter_step`` を使う (silent fallback).

    Lanczos を介さず ``exp(-i·dt·H_drv) = Π_i R_i(dt)`` を閉形式で書く
    operator splitting 経路. LTE は ``O(dt^3)`` で M2 と同じ局所オーダだが,
    per-step コストは ``(N+1)·dim`` 要素アクセス (m=24 の Lanczos より軽い).
    詳細は ``docs/design.md`` §5.3 の Trotter サブセクションを一次資料とする.

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        Trotter 経路は Lanczos を呼ばないため真の matvec カウント概念は
        無いが, ``M2`` ドライバの ``n_steps × m`` と同様の「dim-walk
        見積もり」として ``n_steps × (N + 1)`` (phase pass 1 + bit-flip
        pass N の合計) を返す. ``QuantumResult.n_matvec`` の解釈は
        ``docs/design.md`` §4.4 (Trotter 注記) を参照.

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_trotter_suzuki4(h_x: np.ndarray, h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int) -> tuple[np.ndarray, int]:
    """固定 dt = (t1 - t0) / n_steps の Suzuki S_4 Trotter ドライバ.

    各 step で 5 sub-step の中点 ``t + offset_k · dt`` (``offset_k ∈ [p/2,
    3p/2, 1/2, 1 - 3p/2, 1 - p/2]``) で ``schedule.coeffs_at`` を評価し,
    ``trotter_suzuki4_step`` (Rust) または ``_python_trotter_suzuki4_step``
    (silent fallback) を呼ぶ.

    Lanczos を介さない operator splitting 経路の 4 次版. LTE は ``O(dt^5)``
    で CFM4:2 と同じ局所オーダだが, per-step は ``5·(N + 1)·dim`` 要素アクセス
    (Strang S_2 の 5 倍, M2 の Lanczos m=24 と比べて N の係数次第).
    詳細は ``docs/design.md`` §5.3 (Trotter-Suzuki S_4 サブセクション).

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        Trotter 経路は Lanczos を呼ばないため真の matvec カウント概念は
        無いが, Strang ドライバとの整合のため
        ``n_steps × 5 × (N + 1)`` (5 sub-step × ``phase pass 1 + bit-flip
        pass N``) を返す. ``QuantumResult.n_matvec`` の解釈は
        ``docs/design.md`` §4.4 (Trotter 注記) を参照.

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...
