# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""Krylov + Magnus 時間発展ドライバ.

ここに **公開 driver 関数** (``evolve_schedule_*``) と **Python リファレンス
実装** を置く. Rust 拡張 (``kryanneal._rust``) が利用可能なら fast path に
ディスパッチし, 利用不可なら Python リファレンスで silent fallback する
契約 (詳細は ``docs/design.md`` §3, §5).

提供予定:

* ``evolve_schedule_m2``: 固定 dt の M2 中点則ドライバ.
* ``evolve_schedule_cfm4``: 固定 dt の CFM4:2 ドライバ.
* ``evolve_schedule_adaptive_m2``: M2 embedded error 推定子による
  step-doubling Richardson + PI 制御.
* ``evolve_schedule_adaptive_richardson``: CFM4:2 step-doubling Richardson.

Phase 1 で ``evolve_schedule_m2`` + Python リファレンス実装. Phase 3 で
CFM4:2, Phase 4 で adaptive driver を追加.
"""
from __future__ import annotations as annotations
from typing import Any
__all__: list[str] = []
