# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""アニーリングスケジュール (``Schedule``).

``s(t)`` および ``A(s)`` / ``B(s)`` の時間依存パラメータを 1 つの
``Schedule`` オブジェクトに集約する. 公開コンストラクタ:

* ``Schedule.linear(T)``: 標準的な線形スケジュール ``s(t) = t / T``,
  ``A(s) = 1 - s``, ``B(s) = s``.
* ``Schedule.from_callable(s, A, B, T)``: 任意の callable から構築する
  低レベル API.

Phase 1 で実装予定 (現状は API スケルトン).
"""
from __future__ import annotations as annotations
from typing import Any
__all__: list[str] = []
