# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""``AnnealingSimulator`` — step-wise stateful TFIM 量子ダイナミクスシミュレータ.

設計詳細は ``docs/design.md`` §4.5 を一次資料とする.

``QuantumAnnealer.run`` と同じプロパゲータ集合 (``m2`` / ``trotter`` /
``trotter_suzuki4`` / ``cfm4`` / ``cfm4_adaptive_richardson``) を内部で使うが,
1 step または部分区間ごとに状態を取り出して ``Observable`` で測れる
step-wise stateful API. 用途は中間時刻で diagnostic / observable history を
取りつつ続きを発展させる workflow.

設計判断
--------
* ``__init__`` で ``problem`` / ``schedule`` / ``psi0`` / ``t0`` /
  ``method`` と method 依存パラメータを fix し, 以後の ``step`` /
  ``advance_to`` は内部 ``_t`` / ``_psi`` を逐次更新する.
* ``psi`` プロパティは defensive copy を返し, 戻り値の mutation が
  内部状態に影響しないことを保証する.
* ``measure(observable)`` は read-only なので defensive copy しない
  (``Observable.expectation`` 内で ``abs(psi)**2`` を取るため).
* 数値的に ``QuantumAnnealer.run`` と完全一致 (固定 dt 経路で
  ``rel < 1e-13``) させるため, 内部では同じ ``evolve_schedule_*`` driver
  を呼ぶ. ``step`` は ``n_steps=1`` の薄いラッパ, ``advance_to`` は
  fixed-dt なら ``run`` と同じ driver call.
* adaptive 経路 (``cfm4_adaptive_richardson``) の ``step(dt)`` は
  ``dt`` を PI controller の proposal として渡し, driver 側で reject が
  起これば dt を縮めて再試行 (``dt_max=dt`` で growth を禁じ, ``dt0=dt``
  で初回試行). 結果として ``_t`` は exactly ``+dt`` 進む (1 step(dt) 内に
  複数 internal accept step が発生する可能性あり; その場合 ``n_matvec``
  は累積 m_eff_sum で加算される).
"""
from __future__ import annotations as annotations
from typing import Literal as Literal
import numpy as np
from kryanneal._helpers import _KRYLOV_TOL_ATOL_RATIO as _KRYLOV_TOL_ATOL_RATIO, _KRYLOV_TOL_FIXED_DEFAULT as _KRYLOV_TOL_FIXED_DEFAULT, _resolve_dt_init_auto as _resolve_dt_init_auto, _resolve_dt_max_auto as _resolve_dt_max_auto, _validate_psi0 as _validate_psi0
from kryanneal.krylov import evolve_schedule_adaptive_richardson as evolve_schedule_adaptive_richardson, evolve_schedule_cfm4 as evolve_schedule_cfm4, evolve_schedule_m2 as evolve_schedule_m2, evolve_schedule_trotter as evolve_schedule_trotter, evolve_schedule_trotter_suzuki4 as evolve_schedule_trotter_suzuki4
from kryanneal.observable import Observable as Observable
from kryanneal.problem import IsingProblem as IsingProblem
from kryanneal.schedule import Schedule as Schedule
from typing import Any
__all__ = ['AnnealingSimulator']

class AnnealingSimulator:
    """Step-wise stateful TFIM 量子ダイナミクスシミュレータ.

    Parameters
    ----------
    problem
        ``IsingProblem``. ``H_p_diag`` / ``h_x`` を保持する.
    schedule
        ``Schedule``. ``coeffs_at(t)`` から ``(A(s(t)), B(s(t)))`` を得る.
    psi0
        shape ``(2**n,)`` complex128 の初期状態. L2-normalize 済み
        (``|‖psi0‖ - 1| < 1e-10``) であることを検証する.
    t0
        初期時刻.
    method
        プロパゲータ. ``QuantumAnnealer.run`` と同じ集合をサポート
        (``m2`` / ``trotter`` / ``trotter_suzuki4`` / ``cfm4`` /
        ``cfm4_adaptive_richardson``). default ``"cfm4"``.
    m
        Lanczos / Krylov 部分空間次元. ``m >= 1``. default ``24``.
        ``trotter`` / ``trotter_suzuki4`` 経路では無視される (Lanczos
        非使用).
    krylov_tol
        Lanczos の β 打切り閾値. ``None`` (default) のとき経路ごとに
        自動解決する (QuantumAnnealer と同じポリシー):

        * adaptive 経路: ``effective = tol_step · 1e-3`` (``tol_step``
          は ``atol`` で決まる; default ``atol=1e-8`` → ``1e-11``).
        * 固定 dt 経路: ``1e-12`` (static fallback).
    atol
        adaptive 経路 (``cfm4_adaptive_richardson``) 専用. PI controller
        の局所誤差閾値 ``tol_step``. ``None`` (default) で driver default
        ``1e-8`` を使う. 固定 dt method で指定すると ``ValueError``.
    dt_init
        adaptive 経路専用. ``advance_to`` 時の初期 dt 提案 (driver の
        ``dt0`` に map). ``None`` (default) のとき ``advance_to`` の各
        呼出時に ``T = t_target - _t`` から auto-resolve
        (``c · T^β``, c=0.1, β=0.5, floor=1e-3). ``step(dt)`` の動作には
        影響しない (step は呼出時の ``dt`` を proposal にする). 固定 dt
        method で指定すると ``ValueError``.
    dt_max
        adaptive 経路専用. ``advance_to`` 時の最大 dt 上限 (driver の
        ``dt_max`` に map). ``None`` (default) のとき Gershgorin 上界
        による Lanczos capacity 自動見積もりで auto-resolve.
        ``step(dt)`` では ``dt`` を上限として上書きする (growth 禁止,
        shrinkage 可). 固定 dt method で指定すると ``ValueError``.
    m_max
        adaptive 経路専用. Lanczos 部分空間次元の上限を ``m`` から上書き
        する. ``None`` (default) で ``m`` をそのまま使う. 固定 dt method
        で指定すると ``ValueError``. ``QuantumAnnealer.run`` の ``m_max``
        と同義.

    Raises
    ------
    NotImplementedError
        ``method`` がサポート対象外の場合.
    ValueError
        ``m`` / ``krylov_tol`` / ``atol`` / ``dt_init`` / ``dt_max`` /
        ``m_max`` が範囲外, ``psi0`` の shape / dtype / 非正規化,
        固定 dt method に adaptive 専用パラメータを渡した場合.

    Examples
    --------
    >>> import numpy as np
    >>> from kryanneal import IsingProblem, Observable, Schedule
    >>> from kryanneal.builders import diag_from_J_h
    >>> from kryanneal.initial_states import uniform_superposition
    >>> from kryanneal.simulator import AnnealingSimulator
    >>>
    >>> n = 4
    >>> J = np.zeros((n, n)); J[0, 1] = J[1, 0] = -1.0
    >>> prob = IsingProblem(n=n, H_p_diag=diag_from_J_h(J, np.zeros(n)),
    ...                     h_x=np.ones(n))
    >>> sched = Schedule.linear(T=10.0)
    >>> psi0 = uniform_superposition(n)
    >>> sim = AnnealingSimulator(prob, sched, psi0, 0.0, method="cfm4")
    >>> obs = Observable.magnetization(n)
    >>> sim.advance_to(5.0, n_steps=50)
    >>> mz_mid = sim.measure(obs)
    >>> sim.advance_to(10.0, n_steps=50)
    >>> mz_end = sim.measure(obs)
    """
    problem: Any
    schedule: Any
    _method: Any
    _m: Any
    _krylov_tol_user: Any
    _atol: Any
    _dt_init: Any
    _dt_max: Any
    _m_max: Any
    _t: Any
    _psi: Any
    _n_matvec: Any

    def __init__(self, problem: IsingProblem, schedule: Schedule, psi0: np.ndarray, t0: float, *, method: Literal['m2', 'trotter', 'trotter_suzuki4', 'cfm4', 'cfm4_adaptive_richardson']='cfm4', m: int=24, krylov_tol: float | None=None, atol: float | None=None, dt_init: float | None=None, dt_max: float | None=None, m_max: int | None=None) -> None:
        ...

    @property
    def t(self) -> float:
        """現在時刻."""
        ...

    @property
    def psi(self) -> np.ndarray:
        """現在状態 ``ψ`` の defensive copy (shape ``(2**n,)`` complex128).

        戻り値への mutation は内部状態に影響しない. 内部状態のまま参照
        したい場合は ``measure(observable)`` 経由で観測値を取得する.
        """
        ...

    @property
    def n_matvec(self) -> int:
        """累積 matvec 数 (経路ごとの見積もり; ``QuantumAnnealer.run`` と同規約)."""
        ...

    @property
    def method(self) -> str:
        """選択された propagator method 名 (immutable)."""
        ...

    def step(self, dt: float) -> None:
        """``dt`` だけ進める (1 step).

        固定 dt 経路 (``m2`` / ``trotter`` / ``trotter_suzuki4`` /
        ``cfm4``) では文字通り 1 step (``n_steps=1`` の driver call).
        adaptive 経路 (``cfm4_adaptive_richardson``) では ``dt`` を PI
        controller の proposal として渡し, driver 側で reject が起きれば
        dt を縮めて再試行する. いずれの場合も呼出後の ``_t`` は exactly
        ``+dt`` 進む (adaptive 経路で 1 step(dt) 内に複数 internal accept
        step が発生する可能性があるが, その合計 m_eff_sum が ``n_matvec``
        に加算される).

        Parameters
        ----------
        dt
            正の float. ``dt > 0``.

        Raises
        ------
        ValueError
            ``dt <= 0`` の場合.
        RuntimeError
            adaptive 経路で ``max_rejects`` 連続超過したとき (driver から
            伝播).
        """
        ...

    def advance_to(self, t_target: float, *, n_steps: int | None=None) -> None:
        """``t_target`` まで進める.

        固定 dt 経路では ``n_steps`` 必須 (``QuantumAnnealer.run`` と同じ
        map: ``dt = (t_target - _t) / n_steps``). adaptive 経路では
        ``n_steps`` は None でなければならない (driver が step 数を内部
        決定するため). adaptive 経路の ``dt_init`` / ``dt_max`` /
        ``atol`` / ``m_max`` は ``__init__`` の設定値 (None なら auto
        resolve) を使う.

        Parameters
        ----------
        t_target
            目標時刻. ``t_target > _t`` を要求 (``_t == t_target`` の
            no-op は許容しない: 呼出意図不明確のため明示的に弾く).
        n_steps
            固定 dt method の step 数 (正の整数, 必須). adaptive method
            では None 以外を渡すと ``ValueError``.

        Raises
        ------
        ValueError
            ``t_target <= _t``, 固定 dt で ``n_steps`` 未指定 /
            非正整数, adaptive で ``n_steps`` 非 None の場合.
        RuntimeError
            adaptive 経路で ``max_rejects`` 連続超過したとき.
        """
        ...

    def measure(self, observable: Observable) -> float:
        """現在 ψ で観測量の期待値 ``<ψ|O|ψ>`` を返す (実数).

        ``Observable.expectation`` に内部状態をそのまま渡す
        (``abs(psi)**2`` を取るため read-only; defensive copy 不要).

        Parameters
        ----------
        observable
            ``Observable`` インスタンス. Z 基底対角な Hermitian 演算子.

        Returns
        -------
        float
            ``<ψ|O|ψ>``.

        Raises
        ------
        TypeError
            ``observable`` が ``Observable`` インスタンスでない場合.
        ValueError
            ``observable.diag`` と ψ の shape 不一致 (Observable 側で raise).
        """
        ...
