"""kryanneal 公開 API の per-module ``.pyi`` スタブを生成する.

各公開モジュール (``python/kryanneal/<name>.py``) の AST を走査し,
``python/kryanneal/<name>.pyi`` に以下を出力する:

* モジュール docstring
* top-level imports (アノテーション解決のため verbatim 保持)
* ``__all__`` (定義されていれば)
* 公開関数 / クラス (元ソースの type annotation と **full docstring** を維持)
* dataclass フィールドおよびモジュールレベル定数

公開判定: ``__all__`` があればその集合, 無ければ ``_`` で始まらない名前.

スタブには関数本体を残さず ``docstring`` + ``...`` (``Ellipsis``) で
置き換える. これによりシグネチャと docstring は LLM / 型チェッカ
(`ty` / mypy / pyright) どちらからも一次情報源として利用できる.

再生成:

    uv run python tools/gen_api_stubs.py

``.pre-commit-config.yaml`` の ``gen-api-stubs`` フックが
``python/kryanneal`` 配下または本スクリプト自体の変更時に自動実行する.
差分が出ると pre-commit が失敗するので
``git add python/kryanneal/*.pyi`` して再 commit する.

本スクリプトは cv_ising の ``tools/gen_api_stubs.py`` を kryanneal の
maturin 標準レイアウト (``python-source = "python"``) に合わせて移植した
もの. 実装の本体 (stub_function / stub_class / generate_stub 等) は
cv_ising 側を参照してそのまま流用すること.

NOTE: 本ファイルは Phase 1 で cv_ising から実装本体を移植して埋める.
現状は MODULES リストとパス定数のみが正しい値.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PKG_DIR = REPO_ROOT / "python" / "kryanneal"

# 公開モジュール一覧. ``__init__`` を含む.
MODULES = [
    "__init__",
    "problem",
    "schedule",
    "annealer",
    "krylov",
    "eigenstates",
    "builders",
    "initial_states",
    "result",
    "reference_qutip",
]

HEADER = (
    "# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**\n"
    "# Re-generate with:  uv run python tools/gen_api_stubs.py\n"
)


def main() -> int:
    # TODO(phase1): cv_ising/tools/gen_api_stubs.py から AST ベースの
    # スタブ生成ロジック (find_dunder_all, stub_function, stub_class,
    # generate_stub, _rewrite_import_as_reexport, _ensure_typing_any_import)
    # を移植する. MODULES と PKG_DIR は kryanneal 用に既に合わせてある.
    raise NotImplementedError(
        "Phase 1 で cv_ising/tools/gen_api_stubs.py から実装を移植する. "
        "MODULES / PKG_DIR / HEADER は既に kryanneal レイアウトに合っている."
    )


if __name__ == "__main__":
    sys.exit(main())
