# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""maqina 内部共有ヘルパ (cross-module private API).

``QuantumAnnealer`` (``maqina.annealer``) と ``AnnealingSimulator``
(``maqina.simulator``) の双方で使う共通定数 / 入力検証 / auto
resolution helper を集約する. 本モジュールは **package-internal** で
公開 API ではない (アンダースコア prefix の通称 / ``__all__`` 未宣言).

設計判断 (issue #48 で切り出し)
-------------------------------
* ``maqina.annealer`` は ``__all__ = ["QuantumAnnealer"]`` で public
  surface を絞っているため, そこから private helper を ``simulator.py``
  が module-level で import すると ``annealer.pyi`` (auto-generated)
  には export されておらず ty が解決失敗する.
* 解決策として helper を別モジュール (``_helpers.py``, ``__all__``
  未宣言) に集約し, ``gen_api_stubs.py`` の "``__all__`` 無しなら全
  top-level 名を stub に含める" 規則 (``tools/gen_api_stubs.py``
  ``is_public`` docstring 参照) を活かして両モジュールから安全に共有する.

含まれるもの:

* ``_PSI_NORM_TOL``: ``psi0`` の L2-normalize 許容誤差.
* ``_KRYLOV_TOL_ATOL_RATIO``: adaptive 経路の ``krylov_tol`` を ``atol``
  から導く係数.
* ``_KRYLOV_TOL_FIXED_DEFAULT``: 固定 dt 経路の ``krylov_tol`` static
  fallback.
* ``_AUTO_DT_INIT_C`` / ``_AUTO_DT_INIT_BETA`` / ``_AUTO_DT_INIT_FLOOR``:
  ``dt_init=None`` の T-dep auto resolution パラメータ.
* ``_LANCZOS_DT_NORM_COEFF``: ``dt_max=None`` の Lanczos capacity 上界
  係数.
* ``_gershgorin_norm_upper_bound``: ``‖H(t)‖`` の closed-form 上界.
* ``_resolve_dt_max_auto`` / ``_resolve_dt_init_auto``: auto resolution
  本体.
* ``_validate_psi0``: ``psi0`` 入力検証 (shape / dtype / norm / finite).
"""
from __future__ import annotations as annotations
import numpy as np
from maqina.problem import IsingProblem as IsingProblem
from maqina.schedule import Schedule as Schedule
from typing import Any
_PSI_NORM_TOL: float = 1e-10
_KRYLOV_TOL_ATOL_RATIO: float = 0.001
_KRYLOV_TOL_FIXED_DEFAULT: float = 1e-12
_AUTO_DT_INIT_C: float = 0.1
_AUTO_DT_INIT_BETA: float = 0.5
_AUTO_DT_INIT_FLOOR: float = 0.001
_LANCZOS_DT_NORM_COEFF: float = 4.0

def _validate_psi0(problem: IsingProblem, psi0: np.ndarray) -> np.ndarray:
    """``psi0`` の shape / dtype / L2-norm を検証して C-contiguous で返す.

    ``dim = 2**problem.n`` と整合し, complex128 / C-contiguous で,
    L2 ノルムが 1 から ``_PSI_NORM_TOL`` 以内であることを要求する.
    非 complex128 は明示的にエラーにする (silent cast はしない).

    ``QuantumAnnealer.run`` と ``AnnealingSimulator.__init__`` の両方で
    共有するため module-level に置いている (issue #48 で切り出し).
    """
    ...

def _gershgorin_norm_upper_bound(schedule: Schedule, problem: IsingProblem) -> float:
    """``‖H(t)‖`` の Gershgorin 上界 (closed form, t 非依存; XYZ では端点 sample).

    Phase C / issue #142 で signature を ``(schedule, problem)`` に変更
    (h_x が schedule に移動)。

    - 旧 API (`schedule.is_xyz_api == False`): ``Σ_i |h_x_i| + max_k |H_p_diag[k]|``
      (係数 ``|A|, |B| ≤ 1`` 仮定で安全側. ``Schedule.linear`` 既定で成立).
    - 新 API (`schedule.is_xyz_api == True`): callable は時間依存なので静的上界
      は構築不能. driver 入口の t=0 / 適当な端点で sample した off-diagonal の
      最大値 + ``max_k |H_p_diag[k]|`` を返す保守値. PI controller の
      Richardson breakdown 検出 fail-safe が dt を縮めるので, 多少楽観的でも
      driver 動作自体は安全 (issue #43 B の motivation).

    対角項は ``IsingProblem`` 構築時 precompute 済の
    ``h_p_diag_min`` / ``h_p_diag_max`` から ``max(|min|, |max|)`` で
    closed-form に算出する (O(1)). issue #142 PR #146 follow-up で
    ``np.max(np.abs(...))`` の O(2^N) walk を削除.
    """
    ...

def _resolve_dt_max_auto(schedule: Schedule, problem: IsingProblem, m: int, dt0: float) -> float:
    """``dt_max=None`` (issue #54 で旧 ``"auto"`` リテラル相当) の解決値.
    Lanczos capacity と default の min, dt0 で floor.

    式: ``dt_max = max(min(default_dt_max, 4m / ‖H‖_est), dt0)``,
    ``default_dt_max = 10 · dt0`` (driver default と一致).

    最後の ``max(_, dt0)`` は driver 入力検証 ``dt_max >= dt0`` を満たす
    ための floor. Lanczos cap が ``dt0`` を下回る場合 (``dt0`` が Lanczos
    safe radius を超えているケース) は floor が支配するが, step-doubling
    Richardson 推定子が breakdown を検出して PI controller が dt を
    縮めるので driver 動作自体は安全 (issue #43 B の motivation:
    ``Richardson estimator は Lanczos breakdown も embedded error として
    検出されるので m 自動化 / dt_max 自動化が fail-safe で成立する``).
    """
    ...

def _resolve_dt_init_auto(t0: float, t1: float) -> float:
    """``dt_init=None`` (issue #54 で旧 ``"auto"`` リテラル相当) の解決値
    ``c · T^β`` を返す (T = ``t1 - t0``).

    ``T < 1`` で値が極端に小さくなることを防ぐ床値 ``_AUTO_DT_INIT_FLOOR``
    と, ``dt_init`` が interval ``T`` を超えないようにする上限を同時に張る
    (driver 側の step ループでも ``min(dt, t_end - t)`` で再クランプされる
    が, 初期値で interval を超えないこと自体は driver 入力検証
    ``dt_max >= dt0`` の自然性を保つ).

    issue #43 A の motivation: 線形 schedule では Magnus 級数の T
    スケーリング (s-space scaling invariance, ``docs/design/05-3-propagator.md`` §5.3)
    から最適 dt が T 依存で伸びるため, ``dt_init`` を T 依存に取れば
    PI controller の warmup step (default ``0.5`` → optimal dt への成長)
    を削減できる. 既定 ``c=0.1``, ``β=0.5`` は理論最適 ``β=0.75`` より
    保守的だが warmup の大部分を削減できる中庸値 (issue 本文参照).
    """
    ...
