# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""Krylov + Magnus 時間発展ドライバ.

ここに **公開 driver 関数** (``evolve_schedule_*``) と **Python リファレンス
実装** を置く. Rust 拡張 (``maqina._rust``) が利用可能なら fast path に
ディスパッチし, 利用不可なら Python リファレンスで silent fallback する
契約 (詳細は ``docs/design/03-architecture.md`` §3, §5).

Phase 1 実装範囲
----------------
* ``evolve_schedule_m2``: 固定 dt の M2 中点則ドライバ.
* ``_python_lanczos_propagate``: 純 NumPy の Lanczos 短時間プロパゲータ
  リファレンス.
* ``_python_m2_step``: 純 NumPy の M2 中点則 1 step リファレンス.

Phase 2 で Trotter (Strang 2 次) 経路を追加:

* ``evolve_schedule_trotter``: 固定 dt の Strang Trotter ドライバ.
* ``_python_trotter_step``: 純 NumPy の Strang 1 step リファレンス
  (Rust 拡張 ``_rust.trotter_step_py`` と ``rel < 1e-13`` で一致する契約).

Phase 3 で CFM4:2 (Alvermann-Fehske 2011) 経路を追加:

* ``evolve_schedule_cfm4``: 固定 dt の CFM4:2 (4 次 commutator-free Magnus)
  ドライバ. 各 step で Gauss-Legendre 2 点ノードでスケジュール係数を
  pre-eval し, Rust ``_rust.cfm4_step_py`` (fast path) または
  ``_python_cfm4_step`` (silent fallback) を呼ぶ.
* ``_python_cfm4_step``: 純 NumPy の CFM4:2 1 step リファレンス
  (``_python_lanczos_propagate`` を 2 回呼ぶ; Rust ``_rust.cfm4_step_py``
  と ``rel < 1e-13`` で一致する契約).

Phase 4 で adaptive driver (``evolve_schedule_adaptive_m2`` /
``evolve_schedule_adaptive_richardson``) を追加する.

Rust 拡張へのアクセスは ``maqina._rust`` を **遅延 import** で行う:
``_rust`` のロード失敗 (拡張未ビルド環境) を ``ImportError`` で捕捉して
``_rust`` モジュール参照を ``None`` にし, fast path を選ぶ関数側で
``None`` を見て Python リファレンスにフォールバックする.
"""
from __future__ import annotations as annotations
import importlib
from types import ModuleType as ModuleType
from typing import TYPE_CHECKING as TYPE_CHECKING, Callable as Callable
import numpy as np
from maqina.schedule import Schedule as Schedule
from maqina.observable import Observable as Observable
from typing import Any
SnapshotData = dict[str, 'np.ndarray | dict[str, np.ndarray] | None']
__all__ = ['SnapshotData', 'evolve_schedule_adaptive_m2', 'evolve_schedule_adaptive_richardson', 'evolve_schedule_adaptive_richardson_chebyshev', 'evolve_schedule_cfm4', 'evolve_schedule_m2', 'evolve_schedule_trotter', 'evolve_schedule_trotter_suzuki4']

def evolve_schedule_m2(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int, *, m: int=24, krylov_tol: float=1e-12, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, int, SnapshotData | None]:
    """固定 dt = (t1 - t0) / n_steps の M2 中点則ドライバ.

    各 step で ``schedule.coeffs_at(t + dt/2)`` を評価して
    ``m2_midpoint_step`` を呼ぶ. Rust 拡張が import 済なら
    ``_rust.m2_midpoint_step_py`` を, そうでなければ Python リファレンス
    ``_python_m2_step`` を使う (silent fallback).

    ``save_tlist`` 非 None のとき (Phase 5, issue #47) step boundary 列に
    ``save_tlist`` の各時刻を ``_merge_save_tlist_with_uniform`` で merge
    し, uneven な ``dt`` で進めて該当時刻を厳密に踏む. ``save_tlist=None``
    (default, 最節約モード) では従来通り uniform ``dt`` で進む.

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``). ``save_tlist`` 非 None のとき
        実 step 数は ``n_steps + (save_tlist のうち uniform boundary と
        被らない点の数)`` になる (uneven dt).
    m
        Krylov 部分空間次元.
    krylov_tol
        Lanczos の β 打切り閾値.
    observables
        Phase 5 (issue #47) 追加. ``{name: Observable}`` dict もしくは
        ``None``. ``save_tlist`` 非 None のとき, 各 ``save_tlist[i]`` 時刻で
        ``obs.expectation(psi)`` を評価して snapshot に蓄積する.
        ``save_tlist=None`` のとき silent 無視 (最節約モード).
    save_tlist
        Phase 5 (issue #47) 追加. shape ``(K,)`` float64 の観測時刻列.
        monotonic increasing, ``[t0, t1]`` の範囲. 非 None のとき step
        boundary に merge し snapshot 記録を有効化する. ``None`` (default,
        最節約モード) で snapshot 無し.
    store_states
        Phase 5 (issue #47) 追加. ``True`` かつ ``save_tlist`` 非 None で,
        snapshot 時刻に ψ を保存する. ``save_tlist=None`` のとき無視.

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        累積 matvec 呼出回数 (Lanczos の ``m`` 回 × 実 step 数の見積もり).
    snapshot : SnapshotData | None
        ``save_tlist=None`` のとき ``None``. 非 None のとき dict
        ``{"times": np.ndarray, "observables_history": dict[str, np.ndarray],
        "states": np.ndarray | None}``.

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_trotter(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int, *, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, int, SnapshotData | None]:
    """固定 dt = (t1 - t0) / n_steps の Strang Trotter ドライバ.

    各 step で ``schedule.coeffs_at(t + dt/2)`` を評価して
    ``trotter_step`` を呼ぶ. Rust 拡張が import 済なら
    ``_rust.trotter_step_py`` を, そうでなければ Python リファレンス
    ``_python_trotter_step`` を使う (silent fallback).

    Lanczos を介さず ``exp(-i·dt·H_drv) = Π_i R_i(dt)`` を閉形式で書く
    operator splitting 経路. LTE は ``O(dt^3)`` で M2 と同じ局所オーダだが,
    per-step コストは ``(N+1)·dim`` 要素アクセス (m=24 の Lanczos より軽い).
    詳細は ``docs/design/05-3-propagator.md`` §5.3 の Trotter サブセクションを一次資料とする.

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        Trotter 経路は Lanczos を呼ばないため真の matvec カウント概念は
        無いが, ``M2`` ドライバの ``n_steps × m`` と同様の「dim-walk
        見積もり」として ``n_steps × (N + 1)`` (phase pass 1 + bit-flip
        pass N の合計) を返す. ``QuantumResult.n_matvec`` の解釈は
        ``docs/design/04-python-api.md`` §4.4 (Trotter 注記) を参照.

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_trotter_suzuki4(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int, *, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, int, SnapshotData | None]:
    """固定 dt = (t1 - t0) / n_steps の Suzuki S_4 Trotter ドライバ.

    各 step で 5 sub-step の中点 ``t + offset_k · dt`` (``offset_k ∈ [p/2,
    3p/2, 1/2, 1 - 3p/2, 1 - p/2]``) で ``schedule.coeffs_at`` を評価し,
    ``trotter_suzuki4_step`` (Rust) または ``_python_trotter_suzuki4_step``
    (silent fallback) を呼ぶ.

    Lanczos を介さない operator splitting 経路の 4 次版. LTE は ``O(dt^5)``
    で CFM4:2 と同じ局所オーダだが, per-step は ``5·(N + 1)·dim`` 要素アクセス
    (Strang S_2 の 5 倍, M2 の Lanczos m=24 と比べて N の係数次第).
    詳細は ``docs/design/05-3-propagator.md`` §5.3 (Trotter-Suzuki S_4 サブセクション).

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        Trotter 経路は Lanczos を呼ばないため真の matvec カウント概念は
        無いが, Strang ドライバとの整合のため
        ``n_steps × 5 × (N + 1)`` (5 sub-step × ``phase pass 1 + bit-flip
        pass N``) を返す. ``QuantumResult.n_matvec`` の解釈は
        ``docs/design/04-python-api.md`` §4.4 (Trotter 注記) を参照.

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_cfm4(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, n_steps: int, *, m: int=24, krylov_tol: float=1e-12, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, int, SnapshotData | None]:
    """固定 dt = (t1 - t0) / n_steps の CFM4:2 ドライバ.

    各 step でガウス-ルジャンドル 2 点ノード ``t + c_1·dt`` / ``t + c_2·dt``
    (``c_1, c_2 = 1/2 ∓ √3/6``) で ``schedule.coeffs_at`` を 2 回評価して
    ``(a_s1, b_s1)`` / ``(a_s2, b_s2)`` を pre-eval し, ``cfm4_step`` を呼ぶ.
    Rust 拡張が import 済なら ``_rust.cfm4_step_py`` を, そうでなければ
    Python リファレンス ``_python_cfm4_step`` を使う (silent fallback).

    Alvermann-Fehske (2011) の 4 次 commutator-free Magnus を 1 step ぶん
    適用する. Lanczos を 2 回 / step 呼ぶ (per-step matvec は ``2m``) ので
    M2 中点則 (per-step matvec ``m``) より 2 倍重いが, LTE が ``O(dt^5)`` で
    2 オーダ高精度. 「長時間 / 高精度」要求では同精度比較で総コストが M2 を
    下回るクロスオーバが発生する (``docs/design/05-3-propagator.md`` §5.3 / §12).

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    n_steps
        固定 step 数 (``n_steps >= 1``).
    m
        Krylov 部分空間次元.
    krylov_tol
        Lanczos の β 打切り閾値.

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    n_matvec : int
        累積 matvec 呼出回数 (Lanczos の ``2m`` 回 × ``n_steps`` の見積もり).

    Raises
    ------
    ValueError
        ``n_steps < 1`` または ``t1 <= t0`` のとき.
    """
    ...

def evolve_schedule_adaptive_m2(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, *, m: int=24, krylov_tol: float=1e-12, tol_step: float=1e-08, dt0: float=0.5, dt_min: float=0.0001, dt_max: float | None=None, safety: float=0.9, growth_max: float=4.0, max_rejects: int=50, reject_shrink_min: float=0.2, reject_shrink_max: float=0.9, freeze_growth_after_reject: bool=True, growth_freeze_steps: int=1, save_tlist: np.ndarray | None=None) -> tuple[np.ndarray, np.ndarray, np.ndarray, int]:
    """CFM4:2 + M2 embedded 推定子による adaptive dt ドライバ (Phase 4 C3).

    PI controller (``docs/design/05-3-propagator.md`` §5.3) で local error を ``tol_step``
    以下に保ちつつ dt を伸縮させて ``[t0, t1]`` 区間を進む. 各 step は
    CFM4:2 1 step + M2 1 step (同じ入口 ψ) を走らせ
    ``err = ‖ψ_cfm4 - ψ_m2‖`` を embedded error として PI 制御へ流す.
    accept 時の ψ は ``ψ_cfm4`` を採用する (``cfm4_step`` 単体呼出と
    bit-exact 一致). M2 embedded は ``p = 2`` 指数 ``1/3`` で更新する.

    Rust 拡張が import 済なら ``_rust.cfm4_step_with_m2_estimate_py`` を,
    そうでなければ Python リファレンス ``_python_cfm4_step_with_m2_estimate``
    を使う (silent fallback).

    Parameters
    ----------
    h_x
        shape ``(n,)`` float64. サイト依存横磁場振幅.
    h_p_diag
        shape ``(2**n,)`` float64. Z 基底 problem 対角.
    schedule
        ``Schedule`` インスタンス. ``coeffs_at(t)`` から
        ``(A(s(t)), B(s(t)))`` を取り出す.
    psi0
        shape ``(2**n,)`` complex128. 初期状態 (L2-normalize 済みであること).
    t0, t1
        積分区間 ``[t0, t1]``. ``t1 > t0`` を要求.
    m
        Krylov 部分空間次元 (既定 ``24``).
    krylov_tol
        Lanczos の β 打切り閾値 (既定 ``1e-12``).
    tol_step
        accept 判定の局所誤差閾値 (既定 ``1e-8``; 保守寄りの選定根拠は
        ``docs/design/05-3-propagator.md`` §5.3 PI controller defaults 表のノート参照).
    dt0
        初期 dt (既定 ``0.5``).
    dt_min
        最小 dt (ここまで縮めると err に関わらず accept; 既定 ``1e-4``).
    dt_max
        最大 dt. ``None`` のとき ``10 · dt0`` に解決される.
    safety
        PI 安全係数 (既定 ``0.9``).
    growth_max
        1 step での dt 拡大率上限 (既定 ``4.0``).
    max_rejects
        同一 step での連続 reject 上限. 超過で ``RuntimeError``
        (既定 ``50``).
    reject_shrink_min, reject_shrink_max
        reject 時の dt 縮小 factor のクランプ範囲 ``[reject_shrink_min,
        reject_shrink_max]`` (issue #149, 既定 ``[0.2, 0.9]``). reject 時も
        accept と同じ予測式 ``safety · (tol_step / err)^{1/(p+1)}`` で factor を
        出し, この範囲にクランプして ``dt = max(dt_try · factor, dt_min)``
        とする. ``reject_shrink_min = reject_shrink_max = 0.5`` で旧挙動
        (固定半減) を厳密再現. M2 経路は誤差源分離がないため ``err`` を
        そのまま PI 駆動量に使う (p=2).
    freeze_growth_after_reject, growth_freeze_steps
        reject 後の dt 成長凍結 (issue #150, Gustafsson ヒステリシス). ``True``
        (既定) のとき reject 直後から ``growth_freeze_steps`` 回 (既定 ``1``)
        連続 accept するまで, accept 経路の dt 拡大を ``eff_growth_max = 1.0``
        に凍結する (拡大のみ禁止, 縮小は許可). 過剰縮小 → 楽々 accept → 即
        dt 再上昇 → 再 reject のノコギリ波の「再上昇」側を断つ. ``False`` で
        #149 のみ適用した挙動 (reject 直後でも ``growth_max`` まで拡大可) と
        ビット一致. ``growth_freeze_steps >= 1``.
    save_tlist
        Phase 5 拡張対象外 (issue #47 では adaptive Richardson のみ有効化).
        adaptive M2 driver は ``annealer.py`` の facade からは呼ばれない
        内部 API のため scope 外. ``None`` 以外を渡すと
        ``NotImplementedError``.

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    t_history : np.ndarray
        shape ``(K,)`` float64. ``t0`` を含み, 各 accept 後の時刻列.
    dt_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の dt.
    n_rejects : int
        累積 reject 回数 (連続超過とは別; 全 step 合算).

    Raises
    ------
    ValueError
        ``t1 <= t0`` または PI controller の数値引数が範囲外のとき.
    NotImplementedError
        ``save_tlist`` が ``None`` でないとき (本 driver では scope 外).
    RuntimeError
        ``max_rejects`` を連続超過したとき.
    """
    ...

def evolve_schedule_adaptive_richardson(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, *, m: int=24, krylov_tol: float=1e-12, tol_step: float=1e-08, dt0: float=0.5, dt_min: float=0.0001, dt_max: float | None=None, safety: float=0.9, growth_max: float=4.0, max_rejects: int=50, reject_shrink_min: float=0.2, reject_shrink_max: float=0.9, freeze_growth_after_reject: bool=True, growth_freeze_steps: int=1, richardson_extrapolate: bool=False, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, np.ndarray, np.ndarray, int, np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, SnapshotData | None]:
    """CFM4:2 + step-doubling Richardson 推定子による adaptive dt ドライバ.

    PI controller (``docs/design/05-3-propagator.md`` §5.3) で local error を ``tol_step``
    以下に保ちつつ dt を伸縮させて ``[t0, t1]`` 区間を進む. 各 step は
    full-step CFM4:2 (dt) と half-step×2 CFM4:2 (dt/2 を 2 回) を同入口 ψ
    から走らせ ``err = ‖ψ_full - ψ_h2‖`` を 4 次推定子として PI 制御へ流す.
    accept 時の ψ は ``richardson_extrapolate=False`` で ``ψ_h2`` を,
    ``True`` で外挿後の ``ψ_acc = (16·ψ_h2 - ψ_full)/15`` を採用する.
    Richardson は ``p = 4`` 指数 ``1/5`` で更新する.

    per-step matvec は **6m** (Lanczos 呼出 6 回; full 2m + half×2 で 4m).
    smooth schedule では M2 embedded 比 2 オーダ高精度なので許容 dt を
    1~2 桁伸ばせ, 同精度比較で total コストが M2 を下回るクロスオーバが
    出る (``docs/design/05-3-propagator.md`` §5.3 / §12).

    Rust 拡張が import 済なら ``_rust.cfm4_step_with_richardson_estimate_py``
    を, そうでなければ Python リファレンス
    ``_python_cfm4_step_with_richardson_estimate`` を使う (silent fallback).

    Parameters
    ----------
    h_x, h_p_diag, schedule, psi0, t0, t1
        ``evolve_schedule_adaptive_m2`` と同じ.
    m, krylov_tol, tol_step, dt0, dt_min, dt_max, safety, growth_max, max_rejects
        PI controller の既定パラメータ (``docs/design/05-3-propagator.md`` §5.3).
    reject_shrink_min, reject_shrink_max
        reject 時の dt 縮小 factor のクランプ範囲 (issue #149, 既定
        ``[0.2, 0.9]``). reject 時も accept と同じ予測式で factor を出し
        ``[reject_shrink_min, reject_shrink_max]`` にクランプする. 駆動量は
        accept 経路と整合し ``err_magnus = max(0, err - err_{lanczos/cheb}_total)``
        (p=4). ``reject_shrink_min = reject_shrink_max = 0.5`` で旧挙動
        (固定半減) を厳密再現.
    freeze_growth_after_reject, growth_freeze_steps
        reject 後の dt 成長凍結 (issue #150, Gustafsson ヒステリシス). ``True``
        (既定) のとき reject 直後から ``growth_freeze_steps`` 回 (既定 ``1``)
        連続 accept するまで, accept 経路の dt 拡大を ``eff_growth_max = 1.0``
        に凍結する (拡大のみ禁止, 縮小は許可). 過剰縮小 → 楽々 accept → 即
        dt 再上昇 → 再 reject のノコギリ波の「再上昇」側を断つ. ``False`` で
        #149 のみ適用した挙動とビット一致. ``growth_freeze_steps >= 1``.
    richardson_extrapolate
        ``True`` で外挿後の ``ψ_acc`` を accept 時の状態とする
        (実効 6 次精度; 既定 ``False``).
    observables
        Phase 5 (issue #47) 追加. ``{name: Observable}`` dict もしくは
        ``None``. ``save_tlist`` 非 None のとき各 ``save_tlist[i]`` 時刻で
        ``obs.expectation(psi)`` を評価する. ``save_tlist=None`` で silent
        無視 (最節約モード).
    save_tlist
        Phase 5 (issue #47) 追加. shape ``(K,)`` float64 の観測時刻列.
        monotonic increasing, ``[t0, t1]`` の範囲. 非 None のとき adaptive
        の dt を ``next_save_target - t`` でクランプして当該時刻を厳密に
        踏み, snapshot 記録を有効化する. ``None`` (default, 最節約モード)
        で snapshot 無し.
    store_states
        Phase 5 (issue #47) 追加. ``True`` かつ ``save_tlist`` 非 None で,
        snapshot 時刻に ψ を保存する.

    Returns
    -------
    psi_final : np.ndarray
        shape ``(2**n,)`` complex128 の終端状態.
    t_history : np.ndarray
        shape ``(K,)`` float64. ``t0`` を含み, 各 accept 後の時刻列.
    dt_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の dt.
    n_rejects : int
        累積 reject 回数.
    m_eff_history : np.ndarray
        shape ``(K-1,)`` int64. 各 accept された step の Lanczos 部分空間
        次元 ``m_eff`` の合計 (full + half×2 = 6 Lanczos 呼出, ``m_eff_sum
        <= 6m``). issue #52 A で adaptive driver の per-step 実コストを
        ``QuantumResult.m_eff_stats`` (median / min / max / mean) に集計
        するため. β_k 早期打切により ``m_eff < m`` になる step では
        ``m_eff_sum`` が ``6m`` 未満になり, ``n_matvec`` 推定 (現状
        ``n_steps_actual · 6m``) より実コストは小さい.
    beta_m_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の β_m 統計値.
        ``cfm4_step_with_richardson_estimate`` 内部の 6 Lanczos 呼出のうち
        ``err_lanczos_total`` 算出に使われた β_m 上界 (実装は
        ``err_lanczos_total / (‖ψ_in‖·dt·sum(1/m_eff_i))`` 相当の代表値)
        を保存する. issue #93 (Phase 7).
    err_lanczos_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の
        ``err_lanczos_total`` (Lanczos a posteriori 誤差上界の triangle
        inequality 和; Hochbruck-Lubich + 高次補正). issue #93 (Phase 7).
    err_magnus_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の
        ``err_magnus = max(0, err - err_lanczos_total)`` (Magnus 起因の dt
        誤差成分). PI controller の駆動量に使われた値. issue #93 (Phase 7).
    n_krylov_insufficient : int
        累積で ``err_lanczos_total > tol_step`` を検出した step 数 (accept
        / reject 両方をカウント). Krylov 充分性の診断指標で, 大きい場合は
        ``m`` を増やすことを検討すべき. issue #93 (Phase 7).
    snapshot : SnapshotData | None
        ``save_tlist=None`` のとき ``None``. 非 None のとき dict
        ``{"times": np.ndarray, "observables_history": dict[str, np.ndarray],
        "states": np.ndarray | None}``.

    Raises
    ------
    ValueError, RuntimeError
        ``evolve_schedule_adaptive_m2`` と同様.
    """
    ...

def evolve_schedule_adaptive_richardson_chebyshev(h_p_diag: np.ndarray, schedule: Schedule, psi0: np.ndarray, t0: float, t1: float, *, h_p_min: float, h_p_max: float, chebyshev_tol: float=1e-12, tol_step: float=1e-08, dt0: float=0.5, dt_min: float=0.0001, dt_max: float | None=None, safety: float=0.9, growth_max: float=4.0, max_rejects: int=50, reject_shrink_min: float=0.2, reject_shrink_max: float=0.9, freeze_growth_after_reject: bool=True, growth_freeze_steps: int=1, richardson_extrapolate: bool=False, observables: 'dict[str, Observable] | None'=None, save_tlist: np.ndarray | None=None, store_states: bool=False) -> tuple[np.ndarray, np.ndarray, np.ndarray, int, np.ndarray, np.ndarray, np.ndarray, np.ndarray, int, SnapshotData | None]:
    """CFM4:2 + step-doubling Richardson + Chebyshev propagator (issue #122).

    既存 :func:`evolve_schedule_adaptive_richardson` (Lanczos 経路) と
    **同じ PI controller 構造** を維持したまま, 各 stage の短時間プロパゲータ
    を Lanczos から Chebyshev 3 項漸化に差し替えた variant. アルゴリズム軸
    での V matrix (dim × m_max) cache stall 回避 + Gram-Schmidt 消滅を
    狙う (Phase A POC #120 / PR #121 で per-call 4.45× を実測).

    Rust 拡張 (``_rust.cfm4_step_chebyshev_with_richardson_estimate_py``) が
    必須. Python リファレンス fallback は提供しない (詳細は
    :func:`_adaptive_dispatch_richardson_estimate_chebyshev`).

    PI controller の Magnus 起因駆動量は Lanczos 版と同型:

    .. code-block:: text

        err_magnus = max(0, err - err_chebyshev_total)

    ここで ``err_chebyshev_total`` は full + half×2 の 3 軌道分の Chebyshev
    切り捨て残差 (``2·|J_{K+1}(z)|·‖ψ‖``) を triangle inequality で集約した
    上界. Lanczos 版の ``err_lanczos_total`` と同じ役割.

    Parameters
    ----------
    h_x, h_p_diag, schedule, psi0, t0, t1
        :func:`evolve_schedule_adaptive_richardson` と同じ.
    chebyshev_tol
        Chebyshev 切り捨て次数 ``K_used`` の決定閾値
        (``|J_{K+1}(z)| < chebyshev_tol / 2``). semantics は Lanczos 版の
        ``krylov_tol`` 同等で, "Krylov 近似の許容誤差" 規約 (issue #98 Phase 8).
        新パラメータは導入せず本 driver 内では ``chebyshev_tol`` 命名のみ
        使う. 既定 ``1e-12``.
    tol_step, dt0, dt_min, dt_max, safety, growth_max, max_rejects,
    reject_shrink_min, reject_shrink_max, freeze_growth_after_reject,
    growth_freeze_steps,
    richardson_extrapolate, observables, save_tlist, store_states
        :func:`evolve_schedule_adaptive_richardson` と同じ.

    Returns
    -------
    psi_final, t_history, dt_history, n_rejects
        :func:`evolve_schedule_adaptive_richardson` と同じ.
    k_used_history : np.ndarray
        shape ``(K-1,)`` int64. 各 accept された step の Chebyshev
        ``K_used`` 合計 (full + half×2 = 6 chebyshev_propagate 呼出の K_used
        合計). Lanczos 版の ``m_eff_history`` に相当 (ただし上界 ``6m`` は
        無く, K_used は ``z = R·dt`` に応じて動的に決まる).
    beta_m_history : np.ndarray
        shape ``(K-1,)`` float64. Chebyshev には β_m に相当する量がないため
        本 driver では常に 0.0 を埋める (型互換のため). Lanczos 版との
        コンシステンシのみ目的.
    err_chebyshev_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の
        ``err_chebyshev_total`` (Chebyshev 切り捨て残差の triangle inequality
        和). Lanczos 版の ``err_lanczos_history`` に相当.
    err_magnus_history : np.ndarray
        shape ``(K-1,)`` float64. 各 accept された step の
        ``err_magnus = max(0, err - err_chebyshev_total)`` (Magnus 起因の dt
        誤差成分). PI controller の駆動量に使われた値.
    n_chebyshev_insufficient : int
        累積で ``err_chebyshev_total > tol_step`` を検出した step 数. Lanczos
        版の ``n_krylov_insufficient`` に相当する診断指標.
    snapshot
        :func:`evolve_schedule_adaptive_richardson` と同じ.

    Raises
    ------
    ValueError, RuntimeError
        :func:`evolve_schedule_adaptive_richardson` と同様.
    NotImplementedError
        Rust 拡張 ``maqina._rust`` が import できなかった場合.
    """
    ...
