# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""TFIM 問題定義 (``IsingProblem``).

``IsingProblem`` は Hamiltonian の **問題側の静的構造** を集約するデータ
クラス. ユーザは以下を渡す:

* ``n``: スピン数
* ``H_p_diag``: shape ``(2^N,)`` float64. Z 基底における problem
  Hamiltonian の対角ベクトル (k-local 多項式は ``builders`` モジュールで
  この形に変換しておく).

issue #142 Phase C で **横磁場振幅 ``h_x`` を Schedule に移管**した
(時間依存係数は ``Schedule`` 側に集約という責任分担). ``IsingProblem`` は
問題側の静的構造 (H_p_diag) のみ保持する pure data container.

shape / dtype / NaN-free / `n` と各次元の整合性は本コンストラクタで検証
する. 物理的取り決め (bit 規約等) は ``docs/design/INDEX.md`` および
``CLAUDE.md`` 「物理的取り決め」節を参照.

Note
----
``@dataclass(frozen=True, eq=False)`` を使う. ``frozen=True`` でフィールドを
不変化するが, ``eq=False`` にする理由は ``H_p_diag`` が ``numpy.ndarray`` で
あり, ``==`` がブロードキャストで array を返すため dataclass 既定の
``__eq__`` (タプル比較) が ``ValueError: The truth value of an array ...``
で破綻するため.
"""
from __future__ import annotations as annotations
from dataclasses import dataclass as dataclass, field as field
import numpy as np
from typing import Any
__all__ = ['IsingProblem']

@dataclass(frozen=True, eq=False)
class IsingProblem:
    """TFIM 問題定義 (immutable データコンテナ).

    Parameters
    ----------
    n
        スピン数. ``2**n`` が Hilbert 空間次元.
    H_p_diag
        shape ``(2**n,)`` float64 の C-contiguous ndarray.
        Z 基底における problem Hamiltonian の対角成分.

    Raises
    ------
    ValueError
        以下のいずれかに該当する場合.

        * ``n`` が 1 以上の整数でない
        * ``H_p_diag.shape != (2**n,)``
        * ``H_p_diag.dtype != float64`` または C-contiguous でない
        * 配列に NaN / inf が含まれる
    """
    n: int
    H_p_diag: np.ndarray
    _h_p_diag_min: float = field(init=False, repr=False, compare=False, default=0.0)
    _h_p_diag_max: float = field(init=False, repr=False, compare=False, default=0.0)

    @staticmethod
    def _validate_real_array(name: str, arr: np.ndarray, expected_shape: tuple[int, ...]) -> None:
        ...

    @property
    def dim(self) -> int:
        """Hilbert 空間次元 ``2**n``."""
        ...

    @property
    def h_p_diag_min(self) -> float:
        """``min(H_p_diag)`` の precompute 値 (Gershgorin 行和下界の対角最小)."""
        ...

    @property
    def h_p_diag_max(self) -> float:
        """``max(H_p_diag)`` の precompute 値 (Gershgorin 行和上界の対角最大)."""
        ...
