# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""アニーリングスケジュール (``Schedule``).

Hamiltonian の **時間依存係数を一手に管理**する:

* 旧 API (`Schedule(T, A, B, h_x, s=None)`): 一様横磁場の TFIM
  ``H(t) = A(s(t)) · H_driver + B(s(t)) · H_problem``,
  ``H_driver = -Σ_i h_x_i · X_i`` (X-only, 静的振幅 ``h_x``).
* 新 API (`Schedule.from_xyz(...)`): per-site/per-axis 時間依存場
  ``H(t) = Σ_i [g_x_i(t)·X_i + g_y_i(t)·Y_i + g_z_i(t)·Z_i] + b(t)·H_p_diag``.

issue #142 Phase C で **h_x 振幅を IsingProblem から Schedule に移管**し
"問題側の静的構造 (H_p_diag) vs. 時間発展係数 (h_x / a_t / b_t / g_x_i 等)"
の責任分担を明確化した. ``IsingProblem`` は ``H_p_diag`` のみ保持.

公開コンストラクタ:

* ``Schedule.linear(T, h_x)``: 線形 ``s(t) = t/T``, ``A(s) = 1-s``, ``B(s) = s``.
* ``Schedule.from_callable(T, A, B, h_x, s=None)``: 任意 callable.
* ``Schedule.reverse(T, h_x, s_init=1.0, s_target=0.5)``: reverse annealing.
* ``Schedule.pause(T, h_x, t_pause, duration)``: pause schedule.
* ``Schedule.from_xyz(T, g_x, b, *, g_y=None, g_z=None)``: per-axis 時間依存場
  (新 API). callable に h_x の振幅は既に組み込み済の前提 (Schedule 内では
  時間関数のみ管理).

内部設計:

* 単一 evaluator ``_eval_stage(t) -> (gx_arr, gy_arr_opt, gz_arr_opt, b_scalar)``.
  旧 API では ``gx_arr = -a_t(t) · h_x`` を per-stage に組み立て (alloc は
  ``(n,)`` 小サイズなので negligible; ``g_y / g_z = None``). 新 API では
  callable list を直接評価.
* ``_h_x_abs_sum`` (旧 API only): ``Σ_i |h_x_i|`` を ``__init__`` 時に precompute.
  Chebyshev propagator の per-stage Gershgorin O(1) cached form
  (``gershgorin_per_stage_x_only``, PR #144) に渡す.
* ``_norm_upper_bound_factor_at(t)``: per-axis 上界 ``Σ_i √(g_x_i(t)² + g_y_i(t)²)``
  を返す (Gershgorin 行和の off-diagonal 寄与). 旧 API では
  ``|a_t(t)| · _h_x_abs_sum``.

実装注: 全 phase で callable のまま per-step 評価する. 評価コストは Lanczos
1 step の <1% のため grid cache 化の ROI が薄い (issue #142 risk 分析).
"""
from __future__ import annotations as annotations
from collections.abc import Callable as Callable, Sequence as Sequence
from typing import Literal as Literal
import numpy as np
from typing import Any
__all__ = ['Schedule']

class Schedule:
    """Annealing schedule. 時間依存係数 (h_x 振幅含む) を保持する.

    旧 API (X-only TFIM 経路) と新 API (per-axis 時間依存場経路) を **単一
    クラスで** サポートする. どちらの構築経路を取ったかは ``_is_xyz_api``
    フラグで判別され, driver は ``_eval_stage(t)`` を共通入口として呼ぶ.

    Parameters (旧 API: ``__init__`` / ``from_callable`` / ``linear`` /
    ``reverse`` / ``pause``)
    --------------------------------------------------------------------
    T : float
        総アニーリング時間 (``T > 0``).
    A : Callable[[float], float]
        Driver 係数 ``A(s)``.
    B : Callable[[float], float]
        Problem 係数 ``B(s)``.
    h_x : np.ndarray
        shape ``(n,)`` float64. サイト依存横磁場の **静的振幅**
        (``H_driver = -Σ_i h_x_i · X_i``). issue #142 で IsingProblem
        から移管された.
    s : Callable[[float], float] | None
        ``s(t)``. ``None`` で線形 ``s(t) = t/T``.

    Parameters (新 API: ``from_xyz``)
    ----------------------------------
    T : float
        総時間.
    g_x : Sequence[Callable[[float], float]]
        per-site の X 軸時間依存係数 (length n). callable に h_x 振幅は既に
        組み込み済の前提.
    b : Callable[[float], float]
        problem Hamiltonian の global envelope.
    g_y, g_z : Sequence[Callable] | None
        per-site の Y / Z 軸時間依存係数 (length n). ``None`` で当該軸 skip
        (Rust 側で real-only SIMD kernel に dispatch).

    Raises
    ------
    ValueError
        ``T <= 0``, ``h_x`` の shape / dtype 不整合, callable list の長さ不一致
        等.
    """
    T: Any
    n: Any
    _kind: Any
    _A: Any
    _B: Any
    _h_x: Any
    _h_x_abs_sum: Any
    _g_x_cbs: Any
    _g_y_cbs: Any
    _g_z_cbs: Any
    _b_cb: Any
    _s: Any

    def __init__(self, T: float, A: Callable[[float], float], B: Callable[[float], float], h_x: np.ndarray, s: Callable[[float], float] | None=None) -> None:
        ...

    @classmethod
    def linear(cls, T: float, h_x: np.ndarray) -> 'Schedule':
        """線形スケジュール ``A(s) = 1 - s, B(s) = s, s(t) = t / T``."""
        ...

    @classmethod
    def from_callable(cls, T: float, A: Callable[[float], float], B: Callable[[float], float], h_x: np.ndarray, s: Callable[[float], float] | None=None) -> 'Schedule':
        """任意の callable から ``Schedule`` を構築する低レベル API (旧 API).

        ``__init__`` と等価.
        """
        ...

    @classmethod
    def reverse(cls, T: float, h_x: np.ndarray, s_init: float=1.0, s_target: float=0.5) -> 'Schedule':
        """Reverse annealing schedule (Crosson-Harrow 2016 流の V 字形)."""
        ...

    @classmethod
    def pause(cls, T: float, h_x: np.ndarray, t_pause: float, duration: float) -> 'Schedule':
        """Pause schedule (King-Carrasquilla 2018 流)."""
        ...

    @classmethod
    def from_xyz(cls, T: float, g_x: Sequence[Callable[[float], float]], b: Callable[[float], float], *, g_y: Sequence[Callable[[float], float]] | None=None, g_z: Sequence[Callable[[float], float]] | None=None) -> 'Schedule':
        """per-site/per-axis 時間依存場の Schedule を構築する (新 API, issue #142).

        Hamiltonian 形:

        .. code-block:: text

            H(t) = Σ_i [g_x_i(t)·X_i + g_y_i(t)·Y_i + g_z_i(t)·Z_i] + b(t)·H_p_diag

        callable に h_x の静的振幅は既に組み込み済の前提
        (例えば旧 API ``g_x_i(t) := -a_t(t) · h_x_i`` 相当を新 API で書くなら
        ``g_x = [lambda t, hi=hi: -(1 - t/T) * hi for hi in h_x]``).

        Parameters
        ----------
        T : float
            総時間 (``T > 0``).
        g_x : Sequence[Callable[[float], float]]
            per-site の X 軸時間依存係数 list (length n).
        b : Callable[[float], float]
            problem Hamiltonian の global envelope.
        g_y, g_z : Sequence[Callable] | None
            per-site の Y / Z 軸時間依存係数. ``None`` で当該軸 skip
            (Rust 側で real-only SIMD kernel に dispatch する fast path).

        Raises
        ------
        ValueError
            ``T <= 0``, ``g_x`` が空 / 非 callable, ``g_y`` / ``g_z`` の長さが
            ``g_x`` と異なる場合.

        Notes
        -----
        Trotter method (``"trotter"`` / ``"trotter_suzuki4"``) は新 API
        Schedule で呼ばれた場合 ``ValueError``. Trotter 経路は実数係数前提
        SIMD で組まれているため XYZ 一般化が scope 外 (issue #142 Out of scope,
        必要時に別 issue で対応).
        """
        ...

    def s_at(self, t: float) -> float:
        """``s(t)`` をスカラーで返す (旧 API only).

        新 API (``from_xyz``) で構築された Schedule では ``s(t)`` の概念が
        ない (callable list が直接時間依存係数を返すため). 呼ぶと
        ``RuntimeError``.
        """
        ...

    def coeffs_at(self, t: float) -> tuple[float, float]:
        """``(A(s(t)), B(s(t)))`` を返す (旧 API only).

        新 API で構築された Schedule では使えない. 呼ぶと ``RuntimeError``.
        旧 API path で QuTiP 参照実装等が ``(a_t, b_t)`` スカラー対を要求する
        ケースで使う.
        """
        ...

    @property
    def is_xyz_api(self) -> bool:
        """新 API (``from_xyz``) で構築されたかどうか.

        driver / annealer 側で Trotter method の入口 ValueError 判定や
        Gershgorin O(1) fast path 分岐に使う.
        """
        ...

    @property
    def h_x(self) -> np.ndarray:
        """サイト依存横磁場の振幅 (旧 API only).

        ``H_driver = -Σ_i h_x_i · X_i``. 新 API では callable に h_x が
        組み込み済なので別途振幅を取り出せず, 呼ぶと ``RuntimeError``.
        """
        ...

    @property
    def h_x_abs_sum(self) -> float:
        """``Σ_i |h_x_i|`` の precompute 値 (旧 API only).

        Chebyshev propagator の Gershgorin 上界 closed-form 計算
        (``gershgorin_per_stage_x_only``) で使う. 新 API では時間依存なので
        static cache 不可 (``_norm_upper_bound_factor_at(t)`` を使う).
        """
        ...

    def _eval_stage(self, t: float) -> tuple[np.ndarray, np.ndarray | None, np.ndarray | None, float]:
        """per-stage の ``(g_x_arr, g_y_arr_opt, g_z_arr_opt, b_scalar)`` を返す.

        driver の CFM4 stage / M2 中点 / Trotter (legacy 経路) で per-step に
        呼ぶ統一 evaluator. 返り値 array はすべて C-contiguous float64 で,
        新規 alloc される (caller 側で in-place 変更しないこと).

        - 旧 API (`_kind == "legacy"`): ``a_t = A(s(t))``, ``b_t = B(s(t))`` を
          評価して ``g_x_arr = -a_t · self._h_x``, ``g_y_arr = g_z_arr = None``,
          ``b_scalar = b_t``. 符号は ``H_drv = -Σ h_x X`` 規約を吸収.
        - 新 API (`_kind == "xyz"`): callable list を per-site に評価して
          ``g_x_arr[i] = self._g_x_cbs[i](t)``, ``g_y_arr / g_z_arr`` も同様
          (callable list が None の axis は ``None`` を返して Rust 側で
          real-only fast path に dispatch).
        """
        ...

    def _norm_upper_bound_factor_at(self, t: float) -> float:
        """Gershgorin 行和 off-diagonal 上界 ``Σ_i √(g_x_i(t)² + g_y_i(t)²)`` を返す.

        Chebyshev propagator の per-stage spectral radius 見積もりに使う
        (driver から ``schedule._norm_upper_bound_factor_at(t)`` で呼ぶ).
        旧 API では ``|a_t(t)| · h_x_abs_sum`` に degenerate.

        ``g_y = None`` の場合は単純な ``Σ_i |g_x_i(t)|`` (X-only 経路).
        新 API path で Y-only / XY 混在を統一的に扱える.
        """
        ...
