# Auto-generated by tools/gen_api_stubs.py. **Do not edit by hand.**
# Re-generate with:  uv run python tools/gen_api_stubs.py

"""``AnnealingSimulator`` — step-wise stateful TFIM 量子ダイナミクスシミュレータ.

設計詳細は ``docs/design/04-python-api.md`` §4.5 を一次資料とする.

``QuantumAnnealer.run`` と同じプロパゲータ集合 (``m2`` / ``trotter`` /
``trotter_suzuki4`` / ``cfm4`` / ``cfm4_adaptive_richardson_krylov`` /
``cfm4_adaptive_richardson_chebyshev``) を内部で使うが, 1 step または部分
区間ごとに状態を取り出して ``Observable`` で測れる step-wise stateful API.
用途は中間時刻で diagnostic / observable history を取りつつ続きを発展させる
workflow.

設計判断
--------
* ``__init__`` で ``problem`` / ``schedule`` / ``psi0`` / ``t0`` /
  ``method`` と method 依存パラメータを fix し, 以後の ``step`` /
  ``advance_to`` は内部 ``_t`` / ``_psi`` を逐次更新する.
* ``psi`` プロパティは defensive copy を返し, 戻り値の mutation が
  内部状態に影響しないことを保証する.
* ``measure(observable)`` は read-only なので defensive copy しない
  (``Observable.expectation`` 内で ``abs(psi)**2`` を取るため).
* 数値的に ``QuantumAnnealer.run`` と完全一致 (固定 dt 経路で
  ``rel < 1e-13``) させるため, 内部では同じ ``evolve_schedule_*`` driver
  を呼ぶ. ``step`` は ``n_steps=1`` の薄いラッパ, ``advance_to`` は
  fixed-dt なら ``run`` と同じ driver call.
* adaptive 経路 (``cfm4_adaptive_richardson_krylov`` /
  ``cfm4_adaptive_richardson_chebyshev``) の ``step(dt)`` は ``dt`` を PI
  controller の proposal として渡し, driver 側で reject が起これば dt を
  縮めて再試行 (``dt_max=dt`` で growth を禁じ, ``dt0=dt`` で初回試行).
  結果として ``_t`` は exactly ``+dt`` 進む (1 step(dt) 内に複数 internal
  accept step が発生する可能性あり; その場合 ``n_matvec`` は累積
  m_eff_sum / K_used_sum で加算される).
"""
from __future__ import annotations as annotations
from typing import Literal as Literal
import numpy as np
from maqina._helpers import _KRYLOV_TOL_ATOL_RATIO as _KRYLOV_TOL_ATOL_RATIO, _KRYLOV_TOL_FIXED_DEFAULT as _KRYLOV_TOL_FIXED_DEFAULT, _resolve_dt_init_auto as _resolve_dt_init_auto, _resolve_dt_max_auto as _resolve_dt_max_auto, _validate_psi0 as _validate_psi0
from maqina.controller import ControllerConfig as ControllerConfig
from maqina.krylov import evolve_schedule_adaptive_richardson as evolve_schedule_adaptive_richardson, evolve_schedule_adaptive_richardson_chebyshev as evolve_schedule_adaptive_richardson_chebyshev, evolve_schedule_cfm4 as evolve_schedule_cfm4, evolve_schedule_m2 as evolve_schedule_m2, evolve_schedule_trotter as evolve_schedule_trotter, evolve_schedule_trotter_suzuki4 as evolve_schedule_trotter_suzuki4
from maqina.observable import Observable as Observable
from maqina.problem import IsingProblem as IsingProblem
from maqina.schedule import Schedule as Schedule
from typing import Any
__all__ = ['AnnealingSimulator']

class AnnealingSimulator:
    """Step-wise stateful TFIM 量子ダイナミクスシミュレータ.

    Parameters
    ----------
    problem
        ``IsingProblem``. ``H_p_diag`` / ``h_x`` を保持する.
    schedule
        ``Schedule``. ``coeffs_at(t)`` から ``(A(s(t)), B(s(t)))`` を得る.
    psi0
        shape ``(2**n,)`` complex128 の初期状態. L2-normalize 済み
        (``|‖psi0‖ - 1| < 1e-10``) であることを検証する.
    t0
        初期時刻.
    method
        プロパゲータ. ``QuantumAnnealer.run`` と同じ集合をサポート
        (``m2`` / ``trotter`` / ``trotter_suzuki4`` / ``cfm4`` /
        ``cfm4_adaptive_richardson_krylov`` /
        ``cfm4_adaptive_richardson_chebyshev``). default は
        ``"cfm4_adaptive_richardson_chebyshev"`` (issue #124,
        Phase B Pareto win に基づく).
    m
        Lanczos / Krylov 部分空間次元. ``m >= 1``. default ``24``.
        ``trotter`` / ``trotter_suzuki4`` / ``cfm4_adaptive_richardson_chebyshev``
        経路では無視される (Lanczos 非使用; Chebyshev は K_used 動的決定).
    propagator_tol
        **短時間プロパゲータ U(dt) の per-step 許容誤差** (issue #135 で
        ``krylov_tol`` から rename). Lanczos 経路では Krylov 近似の許容誤差
        (a posteriori 推定子 ``est = β · |c_last| · |dt| / m`` を
        ``est < propagator_tol`` で切る; issue #98 / Phase 8). Chebyshev
        経路では Chebyshev 切り捨て次数 ``K_used`` を決める許容誤差.
        詳細は ``QuantumAnnealer.propagator_tol`` の docstring 参照.

        ``None`` (default) のとき経路ごとに自動解決する (QuantumAnnealer と
        同じポリシー):

        * adaptive Lanczos (``cfm4_adaptive_richardson_krylov``):
          ``effective = tol_step · 1e-3`` (``tol_step`` は ``atol`` で決まる;
          default ``atol=1e-8`` → ``1e-11``). atol scaling 連動.
        * adaptive Chebyshev (``cfm4_adaptive_richardson_chebyshev``):
          **固定 ``1e-12``** (issue #135 で auto-coupling から変更).
          Chebyshev は K_used の対数依存で auto-coupling の動機が弱く,
          固定値で atol-vs-infidelity の monotonicity を確保する.
        * 固定 dt 経路: ``1e-12`` (static fallback).
    atol
        adaptive 経路 (``cfm4_adaptive_richardson_krylov`` /
        ``cfm4_adaptive_richardson_chebyshev``) 専用. PI controller の局所
        誤差閾値 ``tol_step``. ``None`` (default) で driver default ``1e-8``
        を使う. 固定 dt method で指定すると ``ValueError``.

        **Note (Chebyshev variant の atol 振舞い, issue #124 / #135)**:
        Chebyshev では ``atol`` は **upper bound** として機能し, 実際の精度
        がそれより良くなる場合がある (K_used を ``propagator_tol`` (default
        ``1e-12`` 固定, issue #135) から動的決定するため per-stage 誤差が
        ``tol_step`` より遥かに小さくなり, PI controller が見る誤差は Magnus
        4 次成分のみになる). 詳細は ``QuantumAnnealer.run`` の ``atol``
        docstring 注 + ``docs/design/05-3-propagator.md`` "Chebyshev variant" 節.
    dt_init
        adaptive 経路専用. ``advance_to`` 時の初期 dt 提案 (driver の
        ``dt0`` に map). ``None`` (default) のとき ``advance_to`` の各
        呼出時に ``T = t_target - _t`` から auto-resolve
        (``c · T^β``, c=0.1, β=0.5, floor=1e-3). ``step(dt)`` の動作には
        影響しない (step は呼出時の ``dt`` を proposal にする). 固定 dt
        method で指定すると ``ValueError``.
    dt_max
        adaptive 経路専用. ``advance_to`` 時の最大 dt 上限 (driver の
        ``dt_max`` に map). ``None`` (default) のとき Gershgorin 上界
        による Lanczos capacity 自動見積もりで auto-resolve.
        ``step(dt)`` では ``dt`` を上限として上書きする (growth 禁止,
        shrinkage 可). 固定 dt method で指定すると ``ValueError``.
    m_max
        adaptive 経路専用. Lanczos 部分空間次元の上限を ``m`` から上書き
        する. ``None`` (default) で ``m`` をそのまま使う. 固定 dt method
        で指定すると ``ValueError``. ``QuantumAnnealer.run`` の ``m_max``
        と同義.
    controller
        adaptive 経路専用. PI controller の数値挙動 knob を集約した
        :class:`~maqina.ControllerConfig` (issue #149). ``None`` (default)
        で全 default. ``safety`` / ``growth_max`` / ``max_rejects`` /
        ``dt_min`` / ``reject_shrink_min`` / ``reject_shrink_max`` /
        ``freeze_growth_after_reject`` / ``growth_freeze_steps`` を driver
        に渡す. 固定 dt method で指定すると ``ValueError`` (``QuantumAnnealer.run``
        と違い Simulator は strict). reject 時の dt 縮小が固定 0.5 倍から
        予測式 + クランプに変わり (issue #149), さらに reject 直後の accept で
        dt 拡大を凍結する (issue #150, Gustafsson ヒステリシス, 既定有効) ため
        既定挙動が変わる (破壊的変更). #149 のみ適用は
        ``ControllerConfig(reject_shrink_min=0.5, reject_shrink_max=0.5)``,
        成長凍結のみ無効化は
        ``ControllerConfig(freeze_growth_after_reject=False)``.

    Raises
    ------
    NotImplementedError
        ``method`` がサポート対象外の場合.
    ValueError
        ``m`` / ``propagator_tol`` / ``atol`` / ``dt_init`` / ``dt_max`` /
        ``m_max`` が範囲外, ``psi0`` の shape / dtype / 非正規化,
        固定 dt method に adaptive 専用パラメータ (``controller`` 含む) を
        渡した場合.

    Examples
    --------
    >>> import numpy as np
    >>> from maqina import IsingProblem, Observable, Schedule
    >>> from maqina.builders import diag_from_J_h
    >>> from maqina.initial_states import uniform_superposition
    >>> from maqina.simulator import AnnealingSimulator
    >>>
    >>> n = 4
    >>> J = np.zeros((n, n)); J[0, 1] = J[1, 0] = -1.0
    >>> prob = IsingProblem(n=n, H_p_diag=diag_from_J_h(J, np.zeros(n)),
    ...                     h_x=np.ones(n))
    >>> sched = Schedule.linear(T=10.0)
    >>> psi0 = uniform_superposition(n)
    >>> # default ``method="cfm4_adaptive_richardson_chebyshev"`` を使う場合,
    >>> # ``advance_to`` には ``n_steps`` を渡さない (PI controller が dt を
    >>> # 内部決定する). 固定 dt 経路を使いたい場合は ``method="cfm4"`` 等を
    >>> # 明示し ``advance_to(..., n_steps=N)`` を渡す.
    >>> sim = AnnealingSimulator(prob, sched, psi0, 0.0)
    >>> obs = Observable.magnetization(n)
    >>> sim.advance_to(5.0)
    >>> mz_mid = sim.measure(obs)
    >>> sim.advance_to(10.0)
    >>> mz_end = sim.measure(obs)
    """
    problem: Any
    schedule: Any
    _method: Any
    _m: Any
    _propagator_tol_user: Any
    _atol: Any
    _dt_init: Any
    _dt_max: Any
    _m_max: Any
    _controller: Any
    _t: Any
    _psi: Any
    _n_matvec: Any

    def __init__(self, problem: IsingProblem, schedule: Schedule, psi0: np.ndarray, t0: float, *, method: Literal['m2', 'trotter', 'trotter_suzuki4', 'cfm4', 'cfm4_adaptive_richardson_krylov', 'cfm4_adaptive_richardson_chebyshev']='cfm4_adaptive_richardson_chebyshev', m: int=24, propagator_tol: float | None=None, atol: float | None=None, dt_init: float | None=None, dt_max: float | None=None, m_max: int | None=None, controller: ControllerConfig | None=None) -> None:
        ...

    @property
    def t(self) -> float:
        """現在時刻."""
        ...

    @property
    def psi(self) -> np.ndarray:
        """現在状態 ``ψ`` の defensive copy (shape ``(2**n,)`` complex128).

        戻り値への mutation は内部状態に影響しない. 内部状態のまま参照
        したい場合は ``measure(observable)`` 経由で観測値を取得する.
        """
        ...

    @property
    def n_matvec(self) -> int:
        """累積 matvec 数 (経路ごとの見積もり; ``QuantumAnnealer.run`` と同規約)."""
        ...

    @property
    def method(self) -> str:
        """選択された propagator method 名 (immutable)."""
        ...

    def step(self, dt: float) -> None:
        """``dt`` だけ進める (1 step).

        固定 dt 経路 (``m2`` / ``trotter`` / ``trotter_suzuki4`` /
        ``cfm4``) では文字通り 1 step (``n_steps=1`` の driver call).
        adaptive 経路 (``cfm4_adaptive_richardson_krylov`` /
        ``cfm4_adaptive_richardson_chebyshev``) では ``dt`` を PI controller
        の proposal として渡し, driver 側で reject が起きれば dt を縮めて
        再試行する. いずれの場合も呼出後の ``_t`` は exactly ``+dt`` 進む
        (adaptive 経路で 1 step(dt) 内に複数 internal accept step が発生
        する可能性があるが, その合計 m_eff_sum / K_used_sum が
        ``n_matvec`` に加算される).

        Parameters
        ----------
        dt
            正の float. ``dt > 0``.

        Raises
        ------
        ValueError
            ``dt <= 0`` の場合.
        RuntimeError
            adaptive 経路で ``max_rejects`` 連続超過したとき (driver から
            伝播).
        """
        ...

    def advance_to(self, t_target: float, *, n_steps: int | None=None) -> None:
        """``t_target`` まで進める.

        固定 dt 経路では ``n_steps`` 必須 (``QuantumAnnealer.run`` と同じ
        map: ``dt = (t_target - _t) / n_steps``). adaptive 経路では
        ``n_steps`` は None でなければならない (driver が step 数を内部
        決定するため). adaptive 経路の ``dt_init`` / ``dt_max`` /
        ``atol`` / ``m_max`` は ``__init__`` の設定値 (None なら auto
        resolve) を使う.

        Parameters
        ----------
        t_target
            目標時刻. ``t_target > _t`` を要求 (``_t == t_target`` の
            no-op は許容しない: 呼出意図不明確のため明示的に弾く).
        n_steps
            固定 dt method の step 数 (正の整数, 必須). adaptive method
            では None 以外を渡すと ``ValueError``.

        Raises
        ------
        ValueError
            ``t_target <= _t``, 固定 dt で ``n_steps`` 未指定 /
            非正整数, adaptive で ``n_steps`` 非 None の場合.
        RuntimeError
            adaptive 経路で ``max_rejects`` 連続超過したとき.
        """
        ...

    def measure(self, observable: Observable) -> float:
        """現在 ψ で観測量の期待値 ``<ψ|O|ψ>`` を返す (実数).

        ``Observable.expectation`` に内部状態をそのまま渡す
        (``abs(psi)**2`` を取るため read-only; defensive copy 不要).

        Parameters
        ----------
        observable
            ``Observable`` インスタンス. Z 基底対角な Hermitian 演算子.

        Returns
        -------
        float
            ``<ψ|O|ψ>``.

        Raises
        ------
        TypeError
            ``observable`` が ``Observable`` インスタンスでない場合.
        ValueError
            ``observable.diag`` と ψ の shape 不一致 (Observable 側で raise).
        """
        ...

    def _resolved_propagator_tol_fixed(self) -> float:
        ...

    def _resolved_propagator_tol_adaptive(self, tol_step: float) -> float:
        """adaptive Richardson (Lanczos) 経路の propagator_tol 自動解決.

        Lanczos a posteriori 早期打切は atol scaling で連動するのが望ましい
        ため auto-coupling (``tol_step · _KRYLOV_TOL_ATOL_RATIO``) を採る.
        """
        ...

    def _resolved_propagator_tol_chebyshev_adaptive(self) -> float:
        """adaptive Richardson (Chebyshev variant) 経路の propagator_tol 自動解決.

        issue #135 で auto-coupling (``tol_step · _KRYLOV_TOL_ATOL_RATIO``)
        から **固定値 ``_KRYLOV_TOL_FIXED_DEFAULT`` (= 1e-12)** に変更.
        Chebyshev は ``K_used ~ R·dt + log(1/propagator_tol)`` の対数依存で
        propagator_tol を atol に連動させる動機が弱く, auto-coupling だと
        atol↓ で machine precision 到達後に round-off accumulation で精度が
        悪化する非単調性が発生する.
        """
        ...

    def _run_fixed_dt(self, t_next: float, *, n_steps: int) -> None:
        """固定 dt driver を ``[_t, t_next]`` 区間で呼んで状態更新する.

        ``observables`` / ``save_tlist`` / ``store_states`` は Simulator
        の用途外なので常に default (None / False) を渡す. ``run`` と同じ
        driver を同じ引数で呼ぶため, 同じ schedule 評価点で bit-identical
        な数値が出る.
        """
        ...

    def _run_adaptive(self, t_next: float, *, dt_init_override: float | None=None, dt_max_override: float | None=None) -> None:
        """adaptive Richardson driver を ``[_t, t_next]`` 区間で呼ぶ.

        ``dt_init_override`` / ``dt_max_override`` を渡すと
        ``__init__`` の ``dt_init`` / ``dt_max`` を無視してこちらを使う
        (``step(dt)`` 経路用; 呼出側 ``dt`` を proposal にする).
        override が None なら ``__init__`` の値を使い, それも None なら
        ``QuantumAnnealer.run`` と同じ auto resolution を行う.

        ``n_matvec`` は driver の ``m_eff_history`` 合計で正確に加算する
        (早期打切で ``6m`` upper bound より小さくなる可能性があるため,
        累積コストを正確に追う).
        """
        ...
